export const CHISINAU_LOCALITIES = [
  { localityId: 110, name: 'SEC.BOTANICA' },
  { localityId: 120, name: 'SEC.BUIUCANI' },
  { localityId: 130, name: 'SEC.CENTRU' },
  { localityId: 140, name: 'SEC.CIOCANA' },
  { localityId: 150, name: 'SEC.RISCANI' },
  { localityId: 111, name: 'OR.SINGERA' },
  { localityId: 112, name: 'S.DOBROGEA' },
  { localityId: 113, name: 'S.REVACA' },
  { localityId: 121, name: 'OR.DURLESTI' },
  { localityId: 122, name: 'OR.VATRA' },
  { localityId: 123, name: 'S.CONDRITA' },
  { localityId: 124, name: 'S.GHIDIGHICI' },
  { localityId: 131, name: 'OR.CODRU' },
  { localityId: 141, name: 'OR.VADUL LUI VODA' },
  { localityId: 142, name: 'S.BUBUIECI' },
  { localityId: 143, name: 'S.BIC' },
  { localityId: 144, name: 'S.CRUZESTI' },
  { localityId: 145, name: 'S.CEROBORTA' },
  { localityId: 146, name: 'S.TOHATIN' },
  { localityId: 147, name: 'S.BUNETI' },
  { localityId: 148, name: 'S.CHELTUITORI' },
  { localityId: 149, name: 'S.COLONITA' },
  { localityId: 151, name: 'OR.CRICOVA' },
  { localityId: 152, name: 'S.CIORESCU' },
  { localityId: 153, name: 'S.FAURESTI' },
  { localityId: 154, name: 'S.GOIAN' },
  { localityId: 155, name: 'S.GRATIESTI' },
  { localityId: 156, name: 'S.HULBOACA' },
  { localityId: 1033, name: 'S.HUMULESTI' },
  { localityId: 3120, name: 'S.BUDESTI' },
  { localityId: 3121, name: 'S.VADULENI' },
  { localityId: 3153, name: 'S.STAUCENI' },
  { localityId: 3154, name: 'S.GOIANUL NOU' },
  { localityId: 5511, name: 'S.BACIOI' },
  { localityId: 5512, name: 'S.FRUMUSICA' },
  { localityId: 5513, name: 'S.STRAISTENI' },
  { localityId: 5514, name: 'S.BRAILA' },
  { localityId: 8039, name: 'S.TRUSENI' },
]

const BALTI_LOCALITIES = [
  { localityId: 300, name: 'MUN.BALTI' },
  { localityId: 301, name: 'S.ELIZAVETA' },
  { localityId: 4839, name: 'S.SADOVOE' },
]

const BENDER_LOCALITIES = [
  { localityId: 500, name: 'MUN.BENDER' },
  { localityId: 501, name: 'S.PROTEAGAILOVCA' },
]

const ANENII_NOI_LOCALITIES = [
  { localityId: 502, name: 'S.VARNITA' },
  { localityId: 1001, name: 'OR.ANENII NOI' },
  { localityId: 1012, name: 'S.BOTNARESTI' },
  { localityId: 1014, name: 'S.BULBOACA' },
  { localityId: 1015, name: 'S.CALFA' },
  { localityId: 1017, name: 'S.CHETROSU' },
  { localityId: 1018, name: 'S.CHIRCA' },
  { localityId: 1020, name: 'S.CIOBANOVCA' },
  { localityId: 1021, name: 'S.COBUSCA NOUA' },
  { localityId: 1023, name: 'S.COBUSCA VECHE' },
  { localityId: 1026, name: 'S.DELACAU' },
  { localityId: 1027, name: 'S.FLORENI' },
  { localityId: 1028, name: 'S.GEAMANA' },
  { localityId: 1030, name: 'S.GURA BICULUI' },
  { localityId: 1031, name: 'S.HIRBOVAT' },
  { localityId: 1032, name: 'S.MAXIMOVCA' },
  { localityId: 1034, name: 'S.MERENI' },
  { localityId: 1036, name: 'S.MERENII NOI' },
  { localityId: 1037, name: 'S.PUHACENI' },
  { localityId: 1038, name: 'S.ROSCANI' },
  { localityId: 1041, name: 'S.SPEIA' },
  { localityId: 1042, name: 'S.SERPENI' },
  { localityId: 1043, name: 'S.TELITA' },
  { localityId: 1050, name: 'S.TINTARENI' },
  { localityId: 2328, name: 'S.OCHIUL ROS' },
  { localityId: 1010, name: 'S.BERIOZCHI' },
  { localityId: 1011, name: 'S.HIRBOVATUL NOU' },
  { localityId: 1013, name: 'S.SALCIA' },
  { localityId: 1016, name: 'S.CALFA NOUA' },
  { localityId: 1019, name: 'S.BOTNARESTII NOI' },
  { localityId: 1022, name: 'S.SOCOLENI' },
  { localityId: 1024, name: 'S.FLORESTI' },
  { localityId: 1025, name: 'S.CRETOAIA' },
  { localityId: 1029, name: 'S.BATIC' },
  { localityId: 1039, name: 'S.RUSENI' },
  { localityId: 1040, name: 'S.ALBINITA' },
  { localityId: 1044, name: 'S.TELITA NOUA' },
  { localityId: 1046, name: 'S.TODIRESTI' },
  { localityId: 1047, name: 'S.TROITA NOUA' },
  { localityId: 1048, name: 'S.BALMAZ' },
  { localityId: 1049, name: 'S.MIRNOE' },
  { localityId: 2329, name: 'S.PICUS' },
  { localityId: 2338, name: 'S.ZOLOTIEVCA' },
  { localityId: 2339, name: 'S.LARGA' },
  { localityId: 2340, name: 'S.NICOLAEVCA' },
]

const BASARABEASCA_LOCALITIES = [
  { localityId: 1201, name: 'OR.BASARABEASCA' },
  { localityId: 1210, name: 'S.ABACLIA' },
  { localityId: 1211, name: 'S.BASCALIA' },
  { localityId: 1212, name: 'S.CARABETOVCA' },
  { localityId: 1213, name: 'S.IORDANOVCA' },
  { localityId: 1214, name: 'S.ISERLIA' },
  { localityId: 1218, name: 'S.SADACLIA' },
  { localityId: 1215, name: 'S.BOGDANOVCA' },
  { localityId: 1216, name: 'S.CARABIBER' },
  { localityId: 1217, name: 'S.IVANOVCA' },
]

const BRICENI_LOCALITIES = [
  { localityId: 1401, name: 'OR.BRICENI' },
  { localityId: 1402, name: 'OR.LIPCANI' },
  { localityId: 1410, name: 'S.BALASINESTI' },
  { localityId: 1411, name: 'S.BALCAUTI' },
  { localityId: 1413, name: 'S.BERLINTI' },
  { localityId: 1414, name: 'S.BOGDANESTI' },
  { localityId: 1417, name: 'S.BULBOACA' },
  { localityId: 1419, name: 'S.CARACUSENII VECHI' },
  { localityId: 1420, name: 'S.COLICAUTI' },
  { localityId: 1422, name: 'S.CORJEUTI' },
  { localityId: 1423, name: 'S.COTEALA' },
  { localityId: 1424, name: 'S.COTIUJENI' },
  { localityId: 1425, name: 'S.CRIVA' },
  { localityId: 1426, name: 'S.DREPCAUTI' },
  { localityId: 1427, name: 'S.BELEAVINTI' },
  { localityId: 1428, name: 'S.GRIMANCAUTI' },
  { localityId: 1429, name: 'S.HALAHORA DE SUS' },
  { localityId: 1432, name: 'S.HLINA' },
  { localityId: 1433, name: 'S.LARGA' },
  { localityId: 1435, name: 'S.MARCAUTI' },
  { localityId: 1437, name: 'S.MEDVEJA' },
  { localityId: 1439, name: 'S.MIHAILENI' },
  { localityId: 1441, name: 'S.PERERITA' },
  { localityId: 1442, name: 'S.SIRAUTI' },
  { localityId: 1443, name: 'S.SLOBOZIA-SIRAUTI' },
  { localityId: 1444, name: 'S.TABANI' },
  { localityId: 1445, name: 'S.TETCANI' },
  { localityId: 1446, name: 'S.TREBISAUTI' },
  { localityId: 1412, name: 'S.BOCICAUTI' },
  { localityId: 1415, name: 'S.BEZEDA' },
  { localityId: 1416, name: 'S.GRIMESTI' },
  { localityId: 1418, name: 'S.CARACUSENII NOI' },
  { localityId: 1421, name: 'S.TRESTIENI' },
  { localityId: 1430, name: 'S.CHIRILOVCA' },
  { localityId: 1431, name: 'S.HALAHORA DE JOS' },
  { localityId: 1434, name: 'S.PAVLOVCA' },
  { localityId: 1436, name: 'S.MARCAUTII NOI' },
  { localityId: 1438, name: 'S.SLOBOZIA-MEDVEJA' },
  { localityId: 1440, name: 'S.GROZNITA' },
]

const CAHUL_LOCALITIES = [
  { localityId: 1701, name: 'MUN.CAHUL' },
  { localityId: 1710, name: 'S.ANDRUSUL DE JOS' },
  { localityId: 1711, name: 'S.ANDRUSUL DE SUS' },
  { localityId: 1712, name: 'S.BADICUL MOLDOVENESC' },
  { localityId: 1713, name: 'S.BAURCI-MOLDOVENI' },
  { localityId: 1714, name: 'S.BUCURIA' },
  { localityId: 1716, name: 'S.BURLACU' },
  { localityId: 1718, name: 'S.CHIOSELIA MARE' },
  { localityId: 1720, name: 'S.CRIHANA VECHE' },
  { localityId: 1721, name: 'S.CUCOARA' },
  { localityId: 1724, name: 'S.HULUBOAIA' },
  { localityId: 1725, name: 'S.LARGA NOUA' },
  { localityId: 1727, name: 'S.LEBEDENCO' },
  { localityId: 1730, name: 'S.LOPATICA' },
  { localityId: 1731, name: 'S.LUCESTI' },
  { localityId: 1732, name: 'S.MANTA' },
  { localityId: 1734, name: 'S.MOSCOVEI' },
  { localityId: 1736, name: 'S.PELINEI' },
  { localityId: 1738, name: 'S.ROSU' },
  { localityId: 1739, name: 'S.TARACLIA DE SALCIE' },
  { localityId: 1740, name: 'S.TARTAUL DE SALCIE' },
  { localityId: 1741, name: 'S.TATARESTI' },
  { localityId: 1742, name: 'S.ZIRNESTI' },
  { localityId: 2130, name: 'S.DOINA' },
  { localityId: 8718, name: 'S.BORCEAG' },
  { localityId: 9410, name: 'S.ALEXANDRU IOAN CUZA' },
  { localityId: 9411, name: 'S.BRINZA' },
  { localityId: 9412, name: 'S.BURLACENI' },
  { localityId: 9414, name: 'S.ALEXANDERFELD' },
  { localityId: 9415, name: 'S.CISLITA-PRUT' },
  { localityId: 9416, name: 'S.COLIBASI' },
  { localityId: 9417, name: 'S.GAVANOASA' },
  { localityId: 9420, name: 'S.GIURGIULESTI' },
  { localityId: 9421, name: 'S.IUJNOE' },
  { localityId: 9422, name: 'S.SLOBOZIA MARE' },
  { localityId: 9423, name: 'S.VADUL LUI ISAC' },
  { localityId: 9424, name: 'S.VALENI' },
  { localityId: 1715, name: 'S.TUDORESTI' },
  { localityId: 1717, name: 'S.SPICOASA' },
  { localityId: 1719, name: 'S.COTIHANA' },
  { localityId: 1722, name: 'S.CHIRCANI' },
  { localityId: 1723, name: 'S.FRUMUSICA' },
  { localityId: 1726, name: 'S.LARGA VECHE' },
  { localityId: 1728, name: 'S.HUTULU' },
  { localityId: 1729, name: 'S.URSOAIA' },
  { localityId: 1733, name: 'S.PASCANI' },
  { localityId: 1735, name: 'S.TRIFESTII NOI' },
  { localityId: 1737, name: 'S.SATUC' },
  { localityId: 1743, name: 'S.PAICU' },
  { localityId: 1744, name: 'S.TRETESTI' },
  { localityId: 2131, name: 'S.IASNAIA POLEANA' },
  { localityId: 2150, name: 'S.RUMEANTEV' },
  { localityId: 9413, name: 'S.GRECENI' },
  { localityId: 9418, name: 'S.NICOLAEVCA' },
  { localityId: 9419, name: 'S.VLADIMIROVCA' },
]

const CANTEMIR_LOCALITIES = [
  { localityId: 2101, name: 'OR.CANTEMIR' },
  { localityId: 2110, name: 'S.ANTONESTI' },
  { localityId: 2112, name: 'S.BAIMACLIA' },
  { localityId: 2114, name: 'S.CANIA' },
  { localityId: 2116, name: 'S.CAPACLIA' },
  { localityId: 2117, name: 'S.CHIOSELIA' },
  { localityId: 2119, name: 'S.CIOBALACCIA' },
  { localityId: 2122, name: 'S.CIIETU' },
  { localityId: 2124, name: 'S.CIRPESTI' },
  { localityId: 2125, name: 'S.CISLA' },
  { localityId: 2128, name: 'S.COCIULIA' },
  { localityId: 2129, name: 'S.COSTANGALIA' },
  { localityId: 2132, name: 'S.ENICHIOI' },
  { localityId: 2136, name: 'S.GOTESTI' },
  { localityId: 2137, name: 'S.HARAGIS' },
  { localityId: 2138, name: 'S.LARGUTA' },
  { localityId: 2139, name: 'S.LINGURA' },
  { localityId: 2142, name: 'S.PLESENI' },
  { localityId: 2145, name: 'S.PLOPI' },
  { localityId: 2149, name: 'S.PORUMBESTI' },
  { localityId: 2152, name: 'S.SADIC' },
  { localityId: 2154, name: 'S.STOIANOVCA' },
  { localityId: 2155, name: 'S.SAMALIA' },
  { localityId: 2156, name: 'S.TARTAUL' },
  { localityId: 2157, name: 'S.TOCENI' },
  { localityId: 2158, name: 'S.TIGANCA' },
  { localityId: 2161, name: 'S.VISNIOVCA' },
  { localityId: 2111, name: 'S.LECA' },
  { localityId: 2113, name: 'S.ACUI' },
  { localityId: 2115, name: 'S.IEPURENI' },
  { localityId: 2118, name: 'S.TARANCUTA' },
  { localityId: 2120, name: 'S.FLOCOASA' },
  { localityId: 2121, name: 'S.VICTOROVCA' },
  { localityId: 2123, name: 'S.DIMITROVA' },
  { localityId: 2126, name: 'S.SUHAT' },
  { localityId: 2127, name: 'S.SOFRANOVCA' },
  { localityId: 2133, name: 'S.BOBOCICA' },
  { localityId: 2134, name: 'S.FLORICICA' },
  { localityId: 2135, name: 'S.TOLICA' },
  { localityId: 2140, name: 'S.CRACIUN' },
  { localityId: 2141, name: 'S.POPOVCA' },
  { localityId: 2143, name: 'S.HANASENI' },
  { localityId: 2144, name: 'S.TATARASENI' },
  { localityId: 2146, name: 'S.ALEXANDROVCA' },
  { localityId: 2147, name: 'S.HIRTOP' },
  { localityId: 2148, name: 'S.TARACLIA (com. Plopi)' },
  { localityId: 2151, name: 'S.CONSTANTINESTI' },
  { localityId: 2153, name: 'S.TARACLIA (com. Sadic)' },
  { localityId: 2159, name: 'S.GHIOLTOSU' },
  { localityId: 2160, name: 'S.TIGANCA NOUA' },
  { localityId: 2162, name: 'S.VILCELE' },
]

const CALARASI_LOCALITIES = [
  { localityId: 2501, name: 'OR.CALARASI' },
  { localityId: 2511, name: 'S.BAHMUT' },
  { localityId: 2513, name: 'S.BRAVICEA' },
  { localityId: 2514, name: 'S.BUDA' },
  { localityId: 2516, name: 'S.CABAIESTI' },
  { localityId: 2517, name: 'S.DERENEU' },
  { localityId: 2520, name: 'S.FRUMOASA' },
  { localityId: 2521, name: 'S.HIROVA' },
  { localityId: 2522, name: 'S.HIRJAUCA' },
  { localityId: 2526, name: 'S.HOGINESTI' },
  { localityId: 2527, name: 'S.HORODISTE' },
  { localityId: 2528, name: 'S.MELESENI' },
  { localityId: 2529, name: 'S.NISCANI' },
  { localityId: 2530, name: 'S.ONISCANI' },
  { localityId: 2533, name: 'S.PAULESTI' },
  { localityId: 2534, name: 'S.PITUSCA' },
  { localityId: 2535, name: 'S.PIRJOLTENI' },
  { localityId: 2536, name: 'S.RACIULA' },
  { localityId: 2538, name: 'S.RADENI' },
  { localityId: 2539, name: 'S.SADOVA' },
  { localityId: 2540, name: 'S.SASENI' },
  { localityId: 2541, name: 'S.SIPOTENI' },
  { localityId: 2543, name: 'S.TEMELEUTI' },
  { localityId: 2544, name: 'S.TUZARA' },
  { localityId: 2546, name: 'S.PETICENI' },
  { localityId: 2548, name: 'S.TIBIRICA' },
  { localityId: 2549, name: 'S.VALCINET' },
  { localityId: 2550, name: 'S.VARZARESTII NOI' },
  { localityId: 2510, name: 'S.ORICOVA' },
  { localityId: 2512, name: 'S.BAHU' },
  { localityId: 2515, name: 'S.URSARI' },
  { localityId: 2518, name: 'S.BULARDA' },
  { localityId: 2519, name: 'S.DUMA' },
  { localityId: 2523, name: 'S.LEORDOAIA' },
  { localityId: 2524, name: 'S.MINDRA' },
  { localityId: 2525, name: 'S.PALANCA' },
  { localityId: 2531, name: 'S.HIRBOVAT' },
  { localityId: 2532, name: 'S.SVERIDA' },
  { localityId: 2537, name: 'S.PARCANI' },
  { localityId: 2542, name: 'S.PODUL LUNG' },
  { localityId: 2545, name: 'S.NOVACI' },
  { localityId: 2547, name: 'S.SELISTEA NOUA' },
  { localityId: 2552, name: 'BAHMUT LOC.C.F.' },
  { localityId: 2553, name: 'S.SCHINOASA' },
]

const CAUSENI_LOCALITIES = [
  { localityId: 703, name: 'S.CREMENCIUG' },
  { localityId: 2301, name: 'OR.CAINARI' },
  { localityId: 2310, name: 'S.BAIMACLIA' },
  { localityId: 2314, name: 'S.CHIRCAIESTII NOI' },
  { localityId: 2317, name: 'S.CIUFLESTI' },
  { localityId: 2318, name: 'S.CIRNATENII NOI' },
  { localityId: 2323, name: 'S.COSCALIA' },
  { localityId: 2330, name: 'S.PERVOMAISC' },
  { localityId: 2336, name: 'S.TARACLIA' },
  { localityId: 2701, name: 'OR.CAUSENI' },
  { localityId: 2710, name: 'S.BACCEALIA' },
  { localityId: 2712, name: 'S.CHIRCAIESTI' },
  { localityId: 2713, name: 'S.CIRNATENI' },
  { localityId: 2714, name: 'S.FIRLADENI' },
  { localityId: 2715, name: 'S.GISCA' },
  { localityId: 2716, name: 'S.GRIGORIEVCA' },
  { localityId: 2717, name: 'S.HAGIMUS' },
  { localityId: 2718, name: 'S.OPACI' },
  { localityId: 2719, name: 'S.PLOPI-STIUBEI' },
  { localityId: 2720, name: 'S.SAITI' },
  { localityId: 2721, name: 'S.SALCUTA' },
  { localityId: 2722, name: 'S.TANATARI' },
  { localityId: 2723, name: 'S.TANATARII NOI' },
  { localityId: 2727, name: 'S.TOCUZ' },
  { localityId: 2728, name: 'S.UCRAINCA' },
  { localityId: 2730, name: 'S.URSOAIA' },
  { localityId: 2731, name: 'S.ZAIM' },
  { localityId: 7612, name: 'S.CHITCANI' },
  { localityId: 7616, name: 'S.COPANCA' },
  { localityId: 8521, name: 'S.GRADINITA' },
  { localityId: 2311, name: 'S.SURCHICENI' },
  { localityId: 2315, name: 'S.BAURCI' },
  { localityId: 2319, name: 'S.SALCUTA NOUA' },
  { localityId: 2331, name: 'S.CONSTANTINOVCA' },
  { localityId: 2332, name: 'S.PLOP' },
  { localityId: 2333, name: 'S.FLORICA' },
  { localityId: 2341, name: 'CAINARI LOC.C.F.' },
  { localityId: 2711, name: 'S.TRICOLICI' },
  { localityId: 2724, name: 'S.FIRLADENII NOI' },
  { localityId: 2725, name: 'S.STEFANESTI' },
  { localityId: 2726, name: 'S.URSOAIA NOUA' },
  { localityId: 2729, name: 'S.ZVIOZDOCICA' },
  { localityId: 2732, name: 'S.MARIANCA DE SUS' },
  { localityId: 2733, name: 'ZAIM LOC.C.F.' },
  { localityId: 7613, name: 'S.MERENESTI' },
  { localityId: 7614, name: 'S.ZAHORNA' },
  { localityId: 8522, name: 'S.LEUNTEA' },
  { localityId: 8523, name: 'S.VALEA VERDE' },
]

const CIMISLIA_LOCALITIES = [
  { localityId: 1219, name: 'S.TROITCOE' },
  { localityId: 2312, name: 'S.BATIR' },
  { localityId: 2320, name: 'S.CODRENI' },
  { localityId: 2901, name: 'OR.CIMISLIA' },
  { localityId: 2910, name: 'S.ALBINA' },
  { localityId: 2914, name: 'S.CENAC' },
  { localityId: 2915, name: 'S.CIUCUR-MINGIR' },
  { localityId: 2917, name: 'S.ECATERINOVCA' },
  { localityId: 2918, name: 'S.GRADISTE' },
  { localityId: 2919, name: 'S.GURA GALBENEI' },
  { localityId: 2920, name: 'S.HIRTOP' },
  { localityId: 2923, name: 'S.IALPUGENI' },
  { localityId: 2926, name: 'S.PORUMBREI' },
  { localityId: 2927, name: 'S.IVANOVCA NOUA' },
  { localityId: 2928, name: 'S.JAVGUR' },
  { localityId: 2931, name: 'S.LIPOVENI' },
  { localityId: 2935, name: 'S.MIHAILOVCA' },
  { localityId: 2936, name: 'S.SAGAIDAC' },
  { localityId: 2937, name: 'S.SATUL NOU' },
  { localityId: 2938, name: 'S.SELEMET' },
  { localityId: 2939, name: 'S.SURIC' },
  { localityId: 2940, name: 'S.TOPALA' },
  { localityId: 2942, name: 'S.VALEA PERJEI' },
  { localityId: 2321, name: 'S.SAGAIDACUL NOU' },
  { localityId: 2322, name: 'S.ZLOTI LOC.ST.CF.' },
  { localityId: 2911, name: 'S.FETITA' },
  { localityId: 2912, name: 'S.BOGDANOVCA NOUA' },
  { localityId: 2913, name: 'S.BOGDANOVCA VECHE' },
  { localityId: 2916, name: 'S.COSTANGALIA' },
  { localityId: 2921, name: 'S.IALPUG' },
  { localityId: 2922, name: 'S.PRISACA' },
  { localityId: 2924, name: 'S.MARIENFELD' },
  { localityId: 2925, name: 'S.IURIEVCA' },
  { localityId: 2929, name: 'S.ARTIMONOVCA' },
  { localityId: 2930, name: 'S.MAXIMENI' },
  { localityId: 2932, name: 'S.MUNTENI' },
  { localityId: 2933, name: 'S.SCHINOSICA' },
  { localityId: 2934, name: 'S.MERENI' },
  { localityId: 2941, name: 'S.DIMITROVCA' },
]

const CRIULENI_LOCALITIES = [
  { localityId: 3101, name: 'OR.CRIULENI' },
  { localityId: 3111, name: 'S.BALABANESTI' },
  { localityId: 3114, name: 'S.BALTATA' },
  { localityId: 3118, name: 'S.BOSCANA' },
  { localityId: 3122, name: 'S.CIMISENI' },
  { localityId: 3123, name: 'S.CORJOVA' },
  { localityId: 3124, name: 'S.COSERNITA' },
  { localityId: 3125, name: 'S.CRUGLIC' },
  { localityId: 3126, name: 'S.DOLINNOE' },
  { localityId: 3129, name: 'S.DRASLICENI' },
  { localityId: 3131, name: 'S.MAGDACESTI' },
  { localityId: 3133, name: 'S.DUBASARII VECHI' },
  { localityId: 3134, name: 'S.HIRTOPUL MARE' },
  { localityId: 3136, name: 'S.HRUSOVA' },
  { localityId: 3139, name: 'S.ISNOVAT' },
  { localityId: 3140, name: 'S.IZBISTE' },
  { localityId: 3141, name: 'S.JEVRENI' },
  { localityId: 3142, name: 'S.MASCAUTI' },
  { localityId: 3143, name: 'S.MICLESTI' },
  { localityId: 3146, name: 'S.ONITCANI' },
  { localityId: 3147, name: 'S.PASCANI' },
  { localityId: 3149, name: 'S.RACULESTI' },
  { localityId: 3151, name: 'S.RISCOVA' },
  { localityId: 3152, name: 'S.SLOBOZIA-DUSCA' },
  { localityId: 3155, name: 'S.ZAICANA' },
  { localityId: 3110, name: 'S.ZOLONCENI' },
  { localityId: 3112, name: 'S.MALAIESTI' },
  { localityId: 3113, name: 'S.MALAIESTII NOI' },
  { localityId: 3115, name: 'S.BALTATA DE SUS' },
  { localityId: 3116, name: 'S.SAGAIDAC' },
  { localityId: 3117, name: 'S.SAGAIDACUL DE SUS' },
  { localityId: 3119, name: 'S.MARDAREUCA' },
  { localityId: 3127, name: 'S.VALEA COLONITEI' },
  { localityId: 3128, name: 'S.VALEA SATULUI' },
  { localityId: 3130, name: 'S.LOGANESTI' },
  { localityId: 3132, name: 'S.RATUS' },
  { localityId: 3135, name: 'S.HIRTOPUL MIC' },
  { localityId: 3137, name: 'S.CHETROASA' },
  { localityId: 3138, name: 'S.CIOPLENI' },
  { localityId: 3144, name: 'S.STETCANI' },
  { localityId: 3145, name: 'S.OHRINCEA' },
  { localityId: 3148, name: 'S.PORUMBENI' },
  { localityId: 3150, name: 'S.BALASESTI' },
]

const DONDUSENI_LOCALITIES = [
  { localityId: 3401, name: 'OR.DONDUSENI' },
  { localityId: 3410, name: 'S.ARIONESTI' },
  { localityId: 3411, name: 'S.BARABOI' },
  { localityId: 3412, name: 'S.BRICENI' },
  { localityId: 3413, name: 'S.CERNOLEUCA' },
  { localityId: 3414, name: 'S.CLIMAUTI' },
  { localityId: 3415, name: 'S.CORBU' },
  { localityId: 3416, name: 'S.CRISCAUTI' },
  { localityId: 3417, name: 'S.DONDUSENI' },
  { localityId: 3418, name: 'S.ELIZAVETOVCA' },
  { localityId: 3422, name: 'S.FRASIN' },
  { localityId: 3425, name: 'S.HORODISTE' },
  { localityId: 3428, name: 'S.MOSANA' },
  { localityId: 3432, name: 'S.PIVNICENI' },
  { localityId: 3433, name: 'S.PLOP' },
  { localityId: 3434, name: 'S.POCROVCA' },
  { localityId: 3435, name: 'S.REDIUL MARE' },
  { localityId: 3437, name: 'S.SCAIENI' },
  { localityId: 3438, name: 'S.SUDARCA' },
  { localityId: 3444, name: 'S.TELESEUCA' },
  { localityId: 3446, name: 'S.TIRNOVA' },
  { localityId: 3449, name: 'S.TAUL' },
  { localityId: 3419, name: 'S.BOROSENI' },
  { localityId: 3423, name: 'S.CARAIMAN' },
  { localityId: 3424, name: 'S.CODRENII NOI' },
  { localityId: 3429, name: 'S.OCTEABRISCOE' },
  { localityId: 3439, name: 'S.BRAICAU' },
  { localityId: 3445, name: 'S.TELESEUCA NOUA' },
  { localityId: 3447, name: 'S.BRICEVA' },
  { localityId: 3448, name: 'S.ELENOVCA' },
]

const DROCHIA_LOCALITIES = [
  { localityId: 3420, name: 'S.FINTINITA' },
  { localityId: 3426, name: 'S.MARAMONOVCA' },
  { localityId: 3427, name: 'S.MINDIC' },
  { localityId: 3601, name: 'OR.DROCHIA' },
  { localityId: 3610, name: 'S.ANTONEUCA' },
  { localityId: 3612, name: 'S.BARONCEA' },
  { localityId: 3614, name: 'S.CHETROSU' },
  { localityId: 3615, name: 'S.COTOVA' },
  { localityId: 3617, name: 'S.DOMINTENI' },
  { localityId: 3618, name: 'S.DROCHIA' },
  { localityId: 3619, name: 'S.GRIBOVA' },
  { localityId: 3620, name: 'S.HASNASENII MARI' },
  { localityId: 3621, name: 'S.HASNASENII NOI' },
  { localityId: 3623, name: 'S.MICIURIN' },
  { localityId: 3624, name: 'S.MOARA DE PIATRA' },
  { localityId: 3625, name: 'S.NICORENI' },
  { localityId: 3626, name: 'S.OCHIUL ALB' },
  { localityId: 3627, name: 'S.PALANCA' },
  { localityId: 3630, name: 'S.PERVOMAISCOE' },
  { localityId: 3631, name: 'S.PETRENI' },
  { localityId: 3633, name: 'S.POPESTII DE JOS' },
  { localityId: 3634, name: 'S.POPESTII DE SUS' },
  { localityId: 3635, name: 'S.SOFIA' },
  { localityId: 3636, name: 'S.SALVIRII VECHI' },
  { localityId: 3639, name: 'S.SURI' },
  { localityId: 3641, name: 'S.TARIGRAD' },
  { localityId: 3642, name: 'S.ZGURITA' },
  { localityId: 7135, name: 'S.PELINIA' },
  { localityId: 3421, name: 'GHIZDITA LOC.C.F.' },
  { localityId: 3611, name: 'S.SERGHEUCA' },
  { localityId: 3613, name: 'S.BARONCEA NOUA' },
  { localityId: 3616, name: 'S.MACAREUCA' },
  { localityId: 3622, name: 'S.LAZO' },
  { localityId: 3628, name: 'S.HOLOSNITA NOUA' },
  { localityId: 3629, name: 'S.SALVIRII NOI' },
  { localityId: 3632, name: 'S.POPESTII NOI' },
  { localityId: 3637, name: 'S.CEAPAEVCA' },
  { localityId: 3638, name: 'S.ILICIOVCA' },
  { localityId: 3640, name: 'S.SURII NOI' },
  { localityId: 7165, name: 'PELINIA LOC.C.F.' },
]

const DUBASARI_LOCALITIES = [
  { localityId: 3810, name: 'S.COCIERI' },
  { localityId: 3816, name: 'S.CORJOVA' },
  { localityId: 3818, name: 'S.COSNITA' },
  { localityId: 3828, name: 'S.DOROTCAIA' },
  { localityId: 3835, name: 'S.HOLERCANI' },
  { localityId: 3837, name: 'S.MARCAUTI' },
  { localityId: 3838, name: 'S.MOLOVATA' },
  { localityId: 3839, name: 'S.MOLOVATA NOUA' },
  { localityId: 3841, name: 'S.OXENTEA' },
  { localityId: 3842, name: 'S.PIRITA' },
  { localityId: 3844, name: 'S.USTIA' },
  { localityId: 3811, name: 'S.VASILIEVCA' },
  { localityId: 3817, name: 'S.MAHALA' },
  { localityId: 3819, name: 'S.POHREBEA' },
  { localityId: 3840, name: 'S.ROGHI' },
]

const EDINET_LOCALITIES = [
  { localityId: 4101, name: 'MUN.EDINET' },
  { localityId: 4102, name: 'OR.CUPCINI' },
  { localityId: 4112, name: 'S.BLESTENI' },
  { localityId: 4114, name: 'S.BRATUSENI' },
  { localityId: 4116, name: 'S.BRINZENI' },
  { localityId: 4117, name: 'S.BADRAGII NOI' },
  { localityId: 4118, name: 'S.BADRAGII VECHI' },
  { localityId: 4120, name: 'S.BURLANESTI' },
  { localityId: 4122, name: 'S.CHETROSICA NOUA' },
  { localityId: 4124, name: 'S.CORPACI' },
  { localityId: 4125, name: 'S.CUCONESTII NOI' },
  { localityId: 4127, name: 'S.FETESTI' },
  { localityId: 4128, name: 'S.GASPAR' },
  { localityId: 4129, name: 'S.GOLENI' },
  { localityId: 4130, name: 'S.GORDINESTI' },
  { localityId: 4131, name: 'S.HANCAUTI' },
  { localityId: 4132, name: 'S.HINCAUTI' },
  { localityId: 4135, name: 'S.HLINAIA' },
  { localityId: 4137, name: 'S.LOPATNIC' },
  { localityId: 4138, name: 'S.PARCOVA' },
  { localityId: 4140, name: 'S.ROTUNDA' },
  { localityId: 4142, name: 'S.RUSENI' },
  { localityId: 4144, name: 'S.STOLNICENI' },
  { localityId: 4145, name: 'S.SOFRINCANI' },
  { localityId: 4146, name: 'S.TEREBNA' },
  { localityId: 4147, name: 'S.TIRNOVA' },
  { localityId: 4148, name: 'S.TRINCA' },
  { localityId: 4149, name: 'S.CONSTANTINOVCA' },
  { localityId: 4151, name: 'S.VIISOARA' },
  { localityId: 4152, name: 'S.ZABRICENI' },
  { localityId: 4153, name: 'S.ALEXEEVCA' },
  { localityId: 6216, name: 'S.CEPELEUTI' },
  { localityId: 4110, name: 'S.CHETROSICA VECHE' },
  { localityId: 4111, name: 'S.ALEXANDRENI' },
  { localityId: 4113, name: 'S.VOLODENI' },
  { localityId: 4115, name: 'S.BRATUSENII NOI' },
  { localityId: 4121, name: 'S.BUZDUGENI' },
  { localityId: 4123, name: 'S.CHIURT' },
  { localityId: 4126, name: 'S.CUCONESTII VECHI' },
  { localityId: 4133, name: 'S.CLISCAUTI' },
  { localityId: 4134, name: 'S.POIANA' },
  { localityId: 4136, name: 'S.GORDINESTII NOI' },
  { localityId: 4139, name: 'S.FINTINA ALBA' },
  { localityId: 4141, name: 'S.HLINAIA MICA' },
  { localityId: 4143, name: 'S.SLOBODCA' },
  { localityId: 4150, name: 'S.IACHIMENI' },
  { localityId: 4154, name: 'S.ONESTI' },
  { localityId: 6217, name: 'S.RINGACI' },
  { localityId: 6218, name: 'S.VANCICAUTI' },
]

const FALESTI_LOCALITIES = [
  { localityId: 4301, name: 'OR.FALESTI' },
  { localityId: 4310, name: 'S.ALBINETUL VECHI' },
  { localityId: 4314, name: 'S.BOCANI' },
  { localityId: 4315, name: 'S.CALINESTI' },
  { localityId: 4316, name: 'S.CHETRIS' },
  { localityId: 4318, name: 'S.HINCESTI' },
  { localityId: 4319, name: 'S.CALUGAR' },
  { localityId: 4323, name: 'S.CIOLACU NOU' },
  { localityId: 4328, name: 'S.EGOROVCA' },
  { localityId: 4330, name: 'S.FALESTII NOI' },
  { localityId: 4332, name: 'S.GLINJENI' },
  { localityId: 4333, name: 'S.HILIUTI' },
  { localityId: 4335, name: 'S.HORESTI' },
  { localityId: 4338, name: 'S.ILENUTA' },
  { localityId: 4339, name: 'S.ISCALAU' },
  { localityId: 4341, name: 'S.CATRANIC' },
  { localityId: 4343, name: 'S.IZVOARE' },
  { localityId: 4344, name: 'S.LOGOFTENI' },
  { localityId: 4345, name: 'S.MARANDENI' },
  { localityId: 4346, name: 'S.MUSTEATA' },
  { localityId: 4347, name: 'S.NATALIEVCA' },
  { localityId: 4353, name: 'S.NAVIRNET' },
  { localityId: 4354, name: 'S.OBREJA VECHE' },
  { localityId: 4356, name: 'S.PIETROSU' },
  { localityId: 4359, name: 'S.PINZARENI' },
  { localityId: 4362, name: 'S.PIRLITA' },
  { localityId: 4363, name: 'S.POMPA' },
  { localityId: 4366, name: 'S.PRUTENI' },
  { localityId: 4370, name: 'S.RAUTEL' },
  { localityId: 4371, name: 'S.RISIPENI' },
  { localityId: 4373, name: 'S.SARATA VECHE' },
  { localityId: 4376, name: 'S.SCUMPIA' },
  { localityId: 4380, name: 'S.TAXOBENI' },
  { localityId: 4311, name: 'S.ALBINETUL NOU' },
  { localityId: 4312, name: 'S.REDIUL DE JOS' },
  { localityId: 4313, name: 'S.REDIUL DE SUS' },
  { localityId: 4317, name: 'S.CHETRISUL NOU' },
  { localityId: 4320, name: 'S.FRUMUSICA' },
  { localityId: 4321, name: 'S.SOCII NOI' },
  { localityId: 4322, name: 'S.SOCII VECHI' },
  { localityId: 4324, name: 'S.CIOLACU VECHI' },
  { localityId: 4325, name: 'S.FAGADAU' },
  { localityId: 4326, name: 'S.POCROVCA' },
  { localityId: 4327, name: 'S.SOLT\u2568\u20A7AIA' },
  { localityId: 4329, name: 'S.CIULUC' },
  { localityId: 4331, name: 'S.PIETROSUL NOU' },
  { localityId: 4334, name: 'S.RAUTELUL NOU' },
  { localityId: 4336, name: 'S.LUCACENI' },
  { localityId: 4337, name: 'S.UNTENI' },
  { localityId: 4340, name: 'S.BURGHELEA' },
  { localityId: 4342, name: 'S.DOLTU' },
  { localityId: 4348, name: 'S.BELEUTI' },
  { localityId: 4349, name: 'S.COMAROVCA' },
  { localityId: 4350, name: 'S.IVANOVCA' },
  { localityId: 4351, name: 'S.POPOVCA' },
  { localityId: 4352, name: 'S.TAPOC' },
  { localityId: 4355, name: 'S.OBREJA NOUA' },
  { localityId: 4357, name: 'S.MAGURA' },
  { localityId: 4358, name: 'S.MAGURA NOUA' },
  { localityId: 4360, name: 'S.MOLDOVEANCA' },
  { localityId: 4361, name: 'S.PINZARENII NOI' },
  { localityId: 4364, name: 'S.PERVOMAISC' },
  { localityId: 4365, name: 'S.SUVOROVCA' },
  { localityId: 4367, name: 'S.CUZMENII VECHI' },
  { localityId: 4368, name: 'S.DRUJINENI' },
  { localityId: 4369, name: 'S.VALEA RUSULUI' },
  { localityId: 4372, name: 'S.BOCSA' },
  { localityId: 4374, name: 'S.HITRESTI' },
  { localityId: 4375, name: 'S.SARATA NOUA' },
  { localityId: 4377, name: 'S.HIRTOP' },
  { localityId: 4378, name: 'S.MAGUREANCA' },
  { localityId: 4379, name: 'S.NICOLAEVCA' },
  { localityId: 4381, name: 'S.HRUBNA NOUA' },
  { localityId: 4382, name: 'S VRANESTI' },
  { localityId: 4383, name: 'S.CATRANIC LOC.ST.C.F.' },
  { localityId: 4384, name: 'FABRICA DE ZAHAR' },
]

const FLORESTI_LOCALITIES = [
  { localityId: 1916, name: 'S.CUHURESTII DE JOS' },
  { localityId: 1918, name: 'S.CUHURESTII DE SUS' },
  { localityId: 1921, name: 'S.CUNICEA' },
  { localityId: 1927, name: 'S.JAPCA' },
  { localityId: 1929, name: 'S.NAPADOVA' },
  { localityId: 1939, name: 'S.SANATAUCA' },
  { localityId: 1942, name: 'S.TEMELEUTI' },
  { localityId: 1943, name: 'S.TIRGUL-VERTIUJENI' },
  { localityId: 1946, name: 'S.VASCAUTI' },
  { localityId: 1949, name: 'S.VERTIUJENI' },
  { localityId: 1950, name: 'S.ZALUCENI' },
  { localityId: 4501, name: 'OR.FLORESTI' },
  { localityId: 4502, name: 'OR.GHINDESTI' },
  { localityId: 4503, name: 'OR.MARCULESTI' },
  { localityId: 4510, name: 'S.ALEXEEVCA' },
  { localityId: 4514, name: 'S.BAHRINESTI' },
  { localityId: 4515, name: 'S.CASUNCA' },
  { localityId: 4516, name: 'S.CERNITA' },
  { localityId: 4517, name: 'S.CIRIPCAU' },
  { localityId: 4518, name: 'S.CIUTULESTI' },
  { localityId: 4522, name: 'S.COSERNITA' },
  { localityId: 4523, name: 'S.DOMULGENI' },
  { localityId: 4524, name: 'S.FRUMUSICA' },
  { localityId: 4527, name: 'S.GHINDESTI' },
  { localityId: 4530, name: 'S.GURA CAMENCII' },
  { localityId: 4533, name: 'S.GURA CAINARULUI' },
  { localityId: 4535, name: 'S.ILICIOVCA' },
  { localityId: 4537, name: 'S.IZVOARE' },
  { localityId: 4540, name: 'S.LUNGA' },
  { localityId: 4541, name: 'S.MARCULESTI' },
  { localityId: 4542, name: 'S.NICOLAEVCA' },
  { localityId: 4544, name: 'S.PRAJILA' },
  { localityId: 4548, name: 'S.PRODANESTI' },
  { localityId: 4550, name: 'S.PUTINESTI' },
  { localityId: 4551, name: 'S.RADULENII VECHI' },
  { localityId: 4552, name: 'S.ROSIETICI' },
  { localityId: 4555, name: 'S.SEVIROVA' },
  { localityId: 4557, name: 'S.STEFANESTI' },
  { localityId: 4559, name: 'S.TRIFANESTI' },
  { localityId: 4561, name: 'S.VARVAREUCA' },
  { localityId: 1917, name: 'S.TIPORDEI' },
  { localityId: 1919, name: 'S.NICOLAEVCA' },
  { localityId: 1920, name: 'S.UNCHITESTI' },
  { localityId: 1928, name: 'S.BURSUC' },
  { localityId: 1947, name: 'S.FAGADAU' },
  { localityId: 1948, name: 'S.OCTEABRISCOE' },
  { localityId: 1951, name: 'UNCHITESTI LOC.C.F.' },
  { localityId: 4511, name: 'S.CHIRILOVCA' },
  { localityId: 4512, name: 'S.DUMITRENI' },
  { localityId: 4513, name: 'S.RADULENII NOI' },
  { localityId: 4519, name: 'S.ION VODA' },
  { localityId: 4520, name: 'S.MARINESTI' },
  { localityId: 4521, name: 'S.SIRBESTI' },
  { localityId: 4525, name: 'S.FRUMUSICA NOUA' },
  { localityId: 4528, name: 'S.HIRTOP' },
  { localityId: 4529, name: 'S.TIRA' },
  { localityId: 4531, name: 'S.BOBULESTI' },
  { localityId: 4532, name: 'S.GVOZDOVA' },
  { localityId: 4534, name: 'S.ZAROJENI' },
  { localityId: 4536, name: 'S.MAISCOE' },
  { localityId: 4538, name: 'S.BEZENI' },
  { localityId: 4539, name: 'S.SCAIENI' },
  { localityId: 4543, name: 'S.VALEA RADOAIEI' },
  { localityId: 4545, name: 'S.ANTONOVCA' },
  { localityId: 4546, name: 'S.FRUNZESTI' },
  { localityId: 4547, name: 'S.MIHAILOVCA' },
  { localityId: 4549, name: 'S.CAPRESTI' },
  { localityId: 4553, name: 'S.CENUSA' },
  { localityId: 4554, name: 'S.ROSIETICII VECHI' },
  { localityId: 4556, name: 'S.IVANOVCA' },
  { localityId: 4558, name: 'S.PRODANESTII VECHI' },
  { localityId: 4560, name: 'S.ALEXANDROVCA' },
  { localityId: 4562, name: 'S.STIRCENI' },
  { localityId: 4563, name: 'TIRA LOC.C.F.' },
]

const GLODENI_LOCALITIES = [
  { localityId: 4801, name: 'OR.GLODENI' },
  { localityId: 4811, name: 'S.BALATINA' },
  { localityId: 4816, name: 'S.CAJBA' },
  { localityId: 4817, name: 'S.CAMENCA' },
  { localityId: 4821, name: 'S.CIUCIULEA' },
  { localityId: 4822, name: 'S.COBANI' },
  { localityId: 4823, name: 'S.CUHNESTI' },
  { localityId: 4827, name: 'S.DANU' },
  { localityId: 4830, name: 'S.DUSMANI' },
  { localityId: 4831, name: 'S.FUNDURII NOI' },
  { localityId: 4832, name: 'S.FUNDURII VECHI' },
  { localityId: 4833, name: 'S.HIJDIENI' },
  { localityId: 4834, name: 'S.IABLOANA' },
  { localityId: 4836, name: 'S.LIMBENII NOI' },
  { localityId: 4837, name: 'S.LIMBENII VECHI' },
  { localityId: 4838, name: 'S.PETRUNEA' },
  { localityId: 4840, name: 'S.STURZOVCA' },
  { localityId: 4841, name: 'S.USTIA' },
  { localityId: 4842, name: 'S.VIISOARA' },
  { localityId: 4810, name: 'S.STIRCEA' },
  { localityId: 4812, name: 'S.CLOCOCENII VECHI' },
  { localityId: 4813, name: 'S.LIPOVAT' },
  { localityId: 4814, name: 'S.TOMESTII NOI' },
  { localityId: 4815, name: 'S.TOMESTII VECHI' },
  { localityId: 4818, name: 'S.BRINZENI' },
  { localityId: 4819, name: 'S.BUTESTI' },
  { localityId: 4820, name: 'S.MOLESTI' },
  { localityId: 4824, name: 'S.BISERICANI' },
  { localityId: 4825, name: 'S.COT' },
  { localityId: 4826, name: 'S.SERGHIENI' },
  { localityId: 4828, name: 'S.CAMENCUTA' },
  { localityId: 4829, name: 'S.NICOLAEVCA' },
  { localityId: 4835, name: 'S.SOROCA' },
  { localityId: 4843, name: 'S.MOARA DOMNEASCA' },
  { localityId: 4844, name: 'S.MOVILENI' },
]

const HINCESTI_LOCALITIES = [
  { localityId: 5301, name: 'MUN.HINCESTI' },
  { localityId: 5310, name: 'S.BALCEANA' },
  { localityId: 5311, name: 'S.BOBEICA' },
  { localityId: 5314, name: 'S.BOGHICENI' },
  { localityId: 5315, name: 'S.BOZIENI' },
  { localityId: 5317, name: 'S.BUJOR' },
  { localityId: 5318, name: 'S.BUTENI' },
  { localityId: 5319, name: 'S.CARACUI' },
  { localityId: 5320, name: 'S.CALMATUI' },
  { localityId: 5324, name: 'S.CARPINENI' },
  { localityId: 5326, name: 'S.CIOARA' },
  { localityId: 5327, name: 'S.COTUL MORII' },
  { localityId: 5328, name: 'S.CRASNOARMEISCOE' },
  { localityId: 5330, name: 'S.DANCU' },
  { localityId: 5331, name: 'S.FIRLADENI' },
  { localityId: 5332, name: 'S.FUNDUL GALBENEI' },
  { localityId: 5333, name: 'S.IVANOVCA' },
  { localityId: 5337, name: 'S.LAPUSNA' },
  { localityId: 5340, name: 'S.LEUSENI' },
  { localityId: 5342, name: 'S.LOGANESTI' },
  { localityId: 5343, name: 'S.MERESENI' },
  { localityId: 5345, name: 'S.MINGIR' },
  { localityId: 5347, name: 'S.MIRESTI' },
  { localityId: 5349, name: 'S.NEGREA' },
  { localityId: 5350, name: 'S.NEMTENI' },
  { localityId: 5351, name: 'S.OBILENI' },
  { localityId: 5352, name: 'S.ONESTI' },
  { localityId: 5354, name: 'S.PASCANI' },
  { localityId: 5356, name: 'S.PERVOMAISCOE' },
  { localityId: 5357, name: 'S.POGANESTI' },
  { localityId: 5359, name: 'S.SARATA-GALBENA' },
  { localityId: 5361, name: 'S.SECARENI' },
  { localityId: 5364, name: 'S.SOFIA' },
  { localityId: 5365, name: 'S.STOLNICENI' },
  { localityId: 5366, name: 'S.SIPOTENI' },
  { localityId: 5367, name: 'S.VOINESCU' },
  { localityId: 6023, name: 'S.CATELENI' },
  { localityId: 6026, name: 'S.CIUCIULENI' },
  { localityId: 6031, name: 'S.DRAGUSENII NOI' },
  { localityId: 5312, name: 'S.DAHNOVICI' },
  { localityId: 5313, name: 'S.DRAGUSENI' },
  { localityId: 5316, name: 'S.DUBOVCA' },
  { localityId: 5321, name: 'S.CARPINEANCA' },
  { localityId: 5322, name: 'S.COROLIOVCA' },
  { localityId: 5323, name: 'S.VALEA FLORII' },
  { localityId: 5325, name: 'S.HORJESTI' },
  { localityId: 5329, name: 'S.TALAIESTI' },
  { localityId: 5334, name: 'S.COSTESTI' },
  { localityId: 5335, name: 'S.FRASIN' },
  { localityId: 5336, name: 'S.SARATENI' },
  { localityId: 5338, name: 'S.ANINI' },
  { localityId: 5339, name: 'S.RUSCA' },
  { localityId: 5341, name: 'S.FETEASCA' },
  { localityId: 5344, name: 'S.SARATA-MERESENI' },
  { localityId: 5346, name: 'S.SEMIONOVCA' },
  { localityId: 5348, name: 'S.CHETROSENI' },
  { localityId: 5353, name: 'S.STRIMBENI' },
  { localityId: 5355, name: 'S.PERENI' },
  { localityId: 5358, name: 'S.MARCHET' },
  { localityId: 5360, name: 'S.BRATIANOVCA' },
  { localityId: 5362, name: 'S.CORNESTI' },
  { localityId: 5363, name: 'S.SECARENII NOI' },
  { localityId: 6032, name: 'S.HORODCA' },
]

const IALOVENI_LOCALITIES = [
  { localityId: 2313, name: 'S.CARBUNA' },
  { localityId: 2316, name: 'S.CIGIRLENI' },
  { localityId: 2324, name: 'S.GANGURA' },
  { localityId: 2334, name: 'S.RAZENI' },
  { localityId: 2337, name: 'S.VARATIC' },
  { localityId: 5501, name: 'OR.IALOVENI' },
  { localityId: 5510, name: 'S.BARDAR' },
  { localityId: 5515, name: 'S.COSTESTI' },
  { localityId: 5516, name: 'S.DANCENI' },
  { localityId: 5517, name: 'S.HANSCA' },
  { localityId: 5518, name: 'S.HORESTI' },
  { localityId: 5519, name: 'S.HORODCA' },
  { localityId: 5520, name: 'S.MALCOCI' },
  { localityId: 5521, name: 'S.MILESTII MICI' },
  { localityId: 5523, name: 'S.MOLESTI' },
  { localityId: 5524, name: 'S.NIMORENI' },
  { localityId: 5525, name: 'S.POJARENI' },
  { localityId: 5526, name: 'S.PUHOI' },
  { localityId: 5527, name: 'S.RUSESTII NOI' },
  { localityId: 5529, name: 'S.SOCITENI' },
  { localityId: 5530, name: 'S.SURUCENI' },
  { localityId: 5531, name: 'S.TIPALA' },
  { localityId: 5534, name: 'S.ULMU' },
  { localityId: 5535, name: 'S.VASIENI' },
  { localityId: 5536, name: 'S.ZIMBRENI' },
  { localityId: 2325, name: 'S.ALEXANDROVCA' },
  { localityId: 2326, name: 'S.HOMUTEANOVCA' },
  { localityId: 2327, name: 'S.MISOVCA' },
  { localityId: 2335, name: 'S.MILESTII NOI' },
  { localityId: 5522, name: 'S.PIATRA ALBA' },
  { localityId: 5528, name: 'S.RUSESTII VECHI' },
  { localityId: 5532, name: 'S.BALTATI' },
  { localityId: 5533, name: 'S.BUDAI' },
  { localityId: 5537, name: 'S.GAURENI' },
]

const LEOVA_LOCALITIES = [
  { localityId: 5701, name: 'OR.LEOVA' },
  { localityId: 5702, name: 'OR.IARGARA' },
  { localityId: 5711, name: 'S.BAIUS' },
  { localityId: 5714, name: 'S.BESTEMAC' },
  { localityId: 5716, name: 'S.BOROGANI' },
  { localityId: 5717, name: 'S.CAZANGIC' },
  { localityId: 5720, name: 'S.CEADIR' },
  { localityId: 5721, name: 'S.CNEAZEVCA' },
  { localityId: 5723, name: 'S.COLIBABOVCA' },
  { localityId: 5724, name: 'S.COVURLUI' },
  { localityId: 5725, name: 'S.CUPCUI' },
  { localityId: 5726, name: 'S.FILIPENI' },
  { localityId: 5727, name: 'S.ROMANOVCA' },
  { localityId: 5728, name: 'S.HANASENII NOI' },
  { localityId: 5730, name: 'S.ORAC' },
  { localityId: 5731, name: 'S.SARATA NOUA' },
  { localityId: 5732, name: 'S.SARATA-RAZESI' },
  { localityId: 5733, name: 'S.SARATENI' },
  { localityId: 5735, name: 'S.SARATICA NOUA' },
  { localityId: 5737, name: 'S.SIRMA' },
  { localityId: 5738, name: 'S.TIGHECI' },
  { localityId: 5740, name: 'S.TOCHILE-RADUCANI' },
  { localityId: 5741, name: 'S.TOMAI' },
  { localityId: 5742, name: 'S.TOMAIUL NOU' },
  { localityId: 5710, name: 'S.MESENI' },
  { localityId: 5712, name: 'S.COCIULIA NOUA' },
  { localityId: 5713, name: 'S.HIRTOP' },
  { localityId: 5715, name: 'S.PITESTI' },
  { localityId: 5718, name: 'S.FRUMUSICA' },
  { localityId: 5719, name: 'S.SELISTE' },
  { localityId: 5722, name: 'S.CIZLAR' },
  { localityId: 5729, name: 'S.NICOLAEVCA' },
  { localityId: 5734, name: 'S.VICTORIA' },
  { localityId: 5736, name: 'S.CIMPUL DREPT' },
  { localityId: 5739, name: 'S.CUPORANI' },
  { localityId: 5743, name: 'S.SARATICA VECHE' },
  { localityId: 5744, name: 'S.VOZNESENI' },
  { localityId: 5745, name: 'S.TROIAN' },
  { localityId: 5746, name: 'S.TROITA' },
  { localityId: 5747, name: 'S. BULG\u2500\u00E9RICA' },
]

const NISPORENI_LOCALITIES = [
  { localityId: 6001, name: 'OR.NISPORENI' },
  { localityId: 6010, name: 'S.BALANESTI' },
  { localityId: 6012, name: 'S.BALAURESTI' },
  { localityId: 6013, name: 'S.BARBOIENI' },
  { localityId: 6014, name: 'S.BOLDURESTI' },
  { localityId: 6017, name: 'S.BOLTUN' },
  { localityId: 6019, name: 'S.BRATULENI' },
  { localityId: 6021, name: 'S.BURSUC' },
  { localityId: 6022, name: 'S.CALIMANESTI' },
  { localityId: 6024, name: 'S.CIORESTI' },
  { localityId: 6027, name: 'S.CIUTESTI' },
  { localityId: 6029, name: 'S.CRISTESTI' },
  { localityId: 6034, name: 'S.GROZESTI' },
  { localityId: 6035, name: 'S.IURCENI' },
  { localityId: 6037, name: 'S.MARINICI' },
  { localityId: 6041, name: 'S.MILESTI' },
  { localityId: 6042, name: 'S.SELISTE' },
  { localityId: 6044, name: 'S.SOLTANESTI' },
  { localityId: 6045, name: 'S.SISCANI' },
  { localityId: 6047, name: 'S.VALEA-TRESTIENI' },
  { localityId: 6052, name: 'S.VARZARESTI' },
  { localityId: 6054, name: 'S.VINATORI' },
  { localityId: 6055, name: 'S.ZBEROAIA' },
  { localityId: 6011, name: 'S.GAURENI' },
  { localityId: 6015, name: 'S.BACSENI' },
  { localityId: 6016, name: 'S.CHILISOAIA' },
  { localityId: 6020, name: 'S.CIRNESTI' },
  { localityId: 6025, name: 'S.VULCANESTI' },
  { localityId: 6028, name: 'S.VALEA NIRNOVEI' },
  { localityId: 6033, name: 'S.DROJDIENI' },
  { localityId: 6036, name: 'S.MIRZOAIA' },
  { localityId: 6038, name: 'S.HELESTENI' },
  { localityId: 6043, name: 'S.PARUCENI' },
  { localityId: 6046, name: 'S.ODAIA' },
  { localityId: 6048, name: 'S.ISAICANI' },
  { localityId: 6049, name: 'S.LUMINITA' },
  { localityId: 6050, name: 'S.ODOBESTI' },
  { localityId: 6051, name: 'S.SELISTENI' },
  { localityId: 6053, name: 'S.SENDRENI' },
]

const OCNITA_LOCALITIES = [
  { localityId: 6201, name: 'OR.OCNITA' },
  { localityId: 6202, name: 'OR.FRUNZA' },
  { localityId: 6203, name: 'OR.OTACI' },
  { localityId: 6210, name: 'S.BIRLADENI' },
  { localityId: 6213, name: 'S.BIRNOVA' },
  { localityId: 6214, name: 'S.CALARASOVCA' },
  { localityId: 6219, name: 'S.CLOCUSNA' },
  { localityId: 6220, name: 'S.CORESTAUTI' },
  { localityId: 6222, name: 'S.DINGENI' },
  { localityId: 6224, name: 'S.GIRBOVA' },
  { localityId: 6226, name: 'S.GRINAUTI-MOLDOVA' },
  { localityId: 6228, name: 'S.HADARAUTI' },
  { localityId: 6229, name: 'S.LENCAUTI' },
  { localityId: 6231, name: 'S.LIPNIC' },
  { localityId: 6233, name: 'S.MERESEUCA' },
  { localityId: 6234, name: 'S.MIHALASENI' },
  { localityId: 6236, name: 'S.NASLAVCEA' },
  { localityId: 6237, name: 'S.OCNITA' },
  { localityId: 6239, name: 'S.SAUCA' },
  { localityId: 6240, name: 'S.UNGURI' },
  { localityId: 6241, name: 'S.VALCINET' },
  { localityId: 6211, name: 'S.PALADEA' },
  { localityId: 6212, name: 'S.RUJNITA' },
  { localityId: 6215, name: 'S.BEREZOVCA' },
  { localityId: 6221, name: 'S.STALINESTI' },
  { localityId: 6223, name: 'S.GRINAUTI' },
  { localityId: 6225, name: 'S.GRINAUTI-RAIA' },
  { localityId: 6227, name: 'S.REDIUL MARE' },
  { localityId: 6230, name: 'S.VEREJENI' },
  { localityId: 6232, name: 'S.PAUSTOVA' },
  { localityId: 6235, name: 'S.GRINAUTI' },
  { localityId: 6238, name: 'S.MAIOVCA' },
  { localityId: 6242, name: 'S.CODRENI' },
]

const ORHEI_LOCALITIES = [
  { localityId: 6401, name: 'MUN.ORHEI' },
  { localityId: 6410, name: 'S.BEREZLOGI' },
  { localityId: 6412, name: 'S.BIESTI' },
  { localityId: 6415, name: 'S.BOLOHAN' },
  { localityId: 6416, name: 'S.BRAVICENI' },
  { localityId: 6417, name: 'S.BULAIESTI' },
  { localityId: 6419, name: 'S.MIRZESTI' },
  { localityId: 6420, name: 'S.CHIPERCENI' },
  { localityId: 6423, name: 'S.CIOCILTENI' },
  { localityId: 6426, name: 'S.CLISOVA' },
  { localityId: 6428, name: 'S.CRIHANA' },
  { localityId: 6431, name: 'S.CUCURUZENI' },
  { localityId: 6432, name: 'S.DONICI' },
  { localityId: 6435, name: 'S.GHETLOVA' },
  { localityId: 6438, name: 'S.ISACOVA' },
  { localityId: 6439, name: 'S.NECULAIEUCA' },
  { localityId: 6440, name: 'S.IVANCEA' },
  { localityId: 6443, name: 'S.JORA DE MIJLOC' },
  { localityId: 6447, name: 'S.MALAIESTI' },
  { localityId: 6449, name: 'S.MITOC' },
  { localityId: 6450, name: 'S.MOROZENI' },
  { localityId: 6452, name: 'S.PELIVAN' },
  { localityId: 6453, name: 'S.PERESECINA' },
  { localityId: 6454, name: 'S.PIATRA' },
  { localityId: 6456, name: 'S.PODGORENI' },
  { localityId: 6457, name: 'S.POHORNICENI' },
  { localityId: 6458, name: 'S.POHREBENI' },
  { localityId: 6461, name: 'S.PUTINTEI' },
  { localityId: 6464, name: 'S.SELISTE' },
  { localityId: 6467, name: 'S.STEP-SOCI' },
  { localityId: 6469, name: 'S.SUSLENI' },
  { localityId: 6470, name: 'S.TELESEU' },
  { localityId: 6471, name: 'S.SAMANANCA' },
  { localityId: 6472, name: 'S.TREBUJENI' },
  { localityId: 6475, name: 'S.VATICI' },
  { localityId: 6478, name: 'S.VISCAUTI' },
  { localityId: 6479, name: 'S.ZORILE' },
  { localityId: 6749, name: 'S.ZAHORENI' },
  { localityId: 6411, name: 'S.HIJDIENI' },
  { localityId: 6413, name: 'S.CIHORENI' },
  { localityId: 6414, name: 'S.SLOBOZIA-HODOROGEA' },
  { localityId: 6418, name: 'S.MIRZACI' },
  { localityId: 6421, name: 'S.ANDREEVCA' },
  { localityId: 6422, name: 'S.VOROTET' },
  { localityId: 6424, name: 'S.FEDOREUCA' },
  { localityId: 6425, name: 'S.CISMEA' },
  { localityId: 6427, name: 'S.CLISOVA NOUA' },
  { localityId: 6429, name: 'S.CUCURUZENII DE SUS' },
  { localityId: 6430, name: 'S.SIROTA' },
  { localityId: 6433, name: 'S.CAMENCEA' },
  { localityId: 6434, name: 'S.POCSESTI' },
  { localityId: 6436, name: 'S.HULBOACA' },
  { localityId: 6437, name: 'S.NOROCENI' },
  { localityId: 6441, name: 'S.BRANESTI' },
  { localityId: 6442, name: 'S.FURCENI' },
  { localityId: 6444, name: 'S.JORA DE JOS' },
  { localityId: 6445, name: 'S.JORA DE SUS' },
  { localityId: 6446, name: 'S.LOPATNA' },
  { localityId: 6448, name: 'S.TIRZIENI' },
  { localityId: 6451, name: 'S.BREANOVA' },
  { localityId: 6455, name: 'S.JELOBOC' },
  { localityId: 6459, name: 'S.IZVOARE' },
  { localityId: 6460, name: 'S.SERCANI' },
  { localityId: 6462, name: 'S.DISCOVA' },
  { localityId: 6463, name: 'S.VIPROVA' },
  { localityId: 6465, name: 'S.LUCASEUCA' },
  { localityId: 6466, name: 'S.MANA' },
  { localityId: 6468, name: 'S.BUDAI' },
  { localityId: 6473, name: 'S.BUTUCENI' },
  { localityId: 6474, name: 'S.MOROVAIA' },
  { localityId: 6476, name: 'S.CURCHI' },
  { localityId: 6477, name: 'S.TABARA' },
  { localityId: 6480, name: 'S.INCULET' },
  { localityId: 6481, name: 'S.OCNITA-RAZESI' },
  { localityId: 6482, name: 'S.OCNITA-TARANI' },
]

const REZINA_LOCALITIES = [
  { localityId: 6701, name: 'OR.REZINA' },
  { localityId: 6712, name: 'S.BUSAUCA' },
  { localityId: 6713, name: 'S.CINISEUTI' },
  { localityId: 6714, name: 'S.COGILNICENI' },
  { localityId: 6715, name: 'S.CUIZAUCA' },
  { localityId: 6716, name: 'S.ECHIMAUTI' },
  { localityId: 6717, name: 'S.GHIDULENI' },
  { localityId: 6720, name: 'S.GORDINESTI' },
  { localityId: 6721, name: 'S.HORODISTE' },
  { localityId: 6723, name: 'S.IGNATEI' },
  { localityId: 6724, name: 'S.LALOVA' },
  { localityId: 6727, name: 'S.MATEUTI' },
  { localityId: 6728, name: 'S.MESENI' },
  { localityId: 6729, name: 'S.MINCENII DE JOS' },
  { localityId: 6731, name: 'S.OTAC' },
  { localityId: 6732, name: 'S.PAPAUTI' },
  { localityId: 6733, name: 'S.LIPCENI' },
  { localityId: 6734, name: 'S.PECISTE' },
  { localityId: 6735, name: 'S.PERENI' },
  { localityId: 6738, name: 'S.PRIPICENI-RAZESI' },
  { localityId: 6740, name: 'S.SAHARNA NOUA' },
  { localityId: 6743, name: 'S.SIRCOVA' },
  { localityId: 6744, name: 'S.SOLONCENI' },
  { localityId: 6746, name: 'S.TRIFESTI' },
  { localityId: 6747, name: 'S.TAREUCA' },
  { localityId: 6710, name: 'S.BOSERNITA' },
  { localityId: 6711, name: 'S.CIORNA' },
  { localityId: 6718, name: 'S.ROSCANII DE JOS' },
  { localityId: 6719, name: 'S.ROSCANII DE SUS' },
  { localityId: 6722, name: 'S.SLOBOZIA-HORODISTE' },
  { localityId: 6725, name: 'S.NISTRENI' },
  { localityId: 6726, name: 'S.TIPOVA' },
  { localityId: 6730, name: 'S.MINCENII DE SUS' },
  { localityId: 6736, name: 'S.ROSCANI' },
  { localityId: 6737, name: 'S.PISCARESTI' },
  { localityId: 6739, name: 'S.PRIPICENI-CURCHI' },
  { localityId: 6741, name: 'S.BUCIUSCA' },
  { localityId: 6742, name: 'S.SAHARNA' },
  { localityId: 6745, name: 'S.TARASOVA' },
  { localityId: 6748, name: 'S.TAHNAUTI' },
  { localityId: 6750, name: 'S.STOHNAIA' },
]

const RISCANI_LOCALITIES = [
  { localityId: 7101, name: 'OR.RISCANI' },
  { localityId: 7111, name: 'S.ALEXANDRESTI' },
  { localityId: 7115, name: 'S.ALUNIS' },
  { localityId: 7116, name: 'S.BOROSENII NOI' },
  { localityId: 7117, name: 'S.BRANISTE' },
  { localityId: 7121, name: 'S.CORLATENI' },
  { localityId: 7122, name: 'OR.COSTESTI' },
  { localityId: 7126, name: 'S.GALASENI' },
  { localityId: 7128, name: 'S.GRINAUTI' },
  { localityId: 7130, name: 'S.HILIUTI' },
  { localityId: 7131, name: 'S.HORODISTE' },
  { localityId: 7132, name: 'S.MALINOVSCOE' },
  { localityId: 7134, name: 'S.MIHAILENI' },
  { localityId: 7136, name: 'S.PETRUSENI' },
  { localityId: 7138, name: 'S.PIRJOTA' },
  { localityId: 7139, name: 'S.POCUIMBENI' },
  { localityId: 7141, name: 'S.POCIUMBAUTI' },
  { localityId: 7142, name: 'S.RACARIA' },
  { localityId: 7145, name: 'S.RECEA' },
  { localityId: 7148, name: 'S.SINGURENI' },
  { localityId: 7149, name: 'S.STURZENI' },
  { localityId: 7150, name: 'S.SAPTEBANI' },
  { localityId: 7151, name: 'S.SUMNA' },
  { localityId: 7154, name: 'S.VASILEUTI' },
  { localityId: 7160, name: 'S.VARATIC' },
  { localityId: 7162, name: 'S.DURUITOAREA NOUA' },
  { localityId: 7163, name: 'S.ZAICANI' },
  { localityId: 7164, name: 'S.NIHORENI' },
  { localityId: 7110, name: 'S.BALANUL NOU' },
  { localityId: 7112, name: 'S.CUCUIETII NOI' },
  { localityId: 7113, name: 'S.CUCUIETII VECHI' },
  { localityId: 7114, name: 'S.IVANESTI' },
  { localityId: 7118, name: 'S.AVRAMENI' },
  { localityId: 7119, name: 'S.RETENI' },
  { localityId: 7120, name: 'S.RETENI-VASILEUTI' },
  { localityId: 7123, name: 'S.DURUITOAREA' },
  { localityId: 7124, name: 'S.DAMASCANI' },
  { localityId: 7125, name: 'S.PROSCURENI' },
  { localityId: 7127, name: 'S.MALAIESTI' },
  { localityId: 7129, name: 'S.CIOBANOVCA' },
  { localityId: 7133, name: 'S.LUPARIA' },
  { localityId: 7137, name: 'S.PASCAUTI' },
  { localityId: 7140, name: 'S.DRUTA' },
  { localityId: 7143, name: 'S.USUREI' },
  { localityId: 7144, name: 'S.RAMAZAN' },
  { localityId: 7146, name: 'S.SLOBOZIA-RECEA' },
  { localityId: 7147, name: 'S.SVERDIAC' },
  { localityId: 7152, name: 'S.BULHAC' },
  { localityId: 7153, name: 'S.CEPARIA' },
  { localityId: 7155, name: 'S.ARMANCA' },
  { localityId: 7156, name: 'S.CIUBARA' },
  { localityId: 7157, name: 'S.MIHAILENII NOI' },
  { localityId: 7158, name: 'S.MOSENI' },
  { localityId: 7159, name: 'S.STIUBEIENI' },
  { localityId: 7161, name: 'S.DUMENI' },
]

const SINGEREI_LOCALITIES = [
  { localityId: 7401, name: 'OR.SINGEREI' },
  { localityId: 7402, name: 'OR.BIRUINTA' },
  { localityId: 7411, name: 'S.ALEXANDRENI' },
  { localityId: 7416, name: 'S.BALASESTI' },
  { localityId: 7417, name: 'S.BILICENII NOI' },
  { localityId: 7420, name: 'S.BILICENII VECHI' },
  { localityId: 7422, name: 'S.BURSUCENI' },
  { localityId: 7424, name: 'S.CHISCARENI' },
  { localityId: 7427, name: 'S.CIUCIUIENI' },
  { localityId: 7429, name: 'S.COPACENI' },
  { localityId: 7433, name: 'S.GRIGORAUCA' },
  { localityId: 7436, name: 'S.COSCODENI' },
  { localityId: 7439, name: 'S.COTIUJENII MICI' },
  { localityId: 7442, name: 'S.CUBOLTA' },
  { localityId: 7443, name: 'S.DOBROGEA VECHE' },
  { localityId: 7446, name: 'S.DRAGANESTI' },
  { localityId: 7449, name: 'S.DUMBRAVITA' },
  { localityId: 7452, name: 'S.HECIUL NOU' },
  { localityId: 7454, name: 'S.IEZARENII VECHI' },
  { localityId: 7456, name: 'S.IZVOARE' },
  { localityId: 7460, name: 'S.PEPENI' },
  { localityId: 7465, name: 'S.PREPELITA' },
  { localityId: 7468, name: 'S.RADOAIA' },
  { localityId: 7469, name: 'S.SINGEREII NOI' },
  { localityId: 7471, name: 'S.TAURA VECHE' },
  { localityId: 4526, name: 'S.MARASESTI' },
  { localityId: 7410, name: 'S.VRANESTI' },
  { localityId: 7412, name: 'S.GRIGORESTI' },
  { localityId: 7413, name: 'S.HECIUL VECHI' },
  { localityId: 7414, name: 'S.TIPLESTI' },
  { localityId: 7415, name: 'S.TIPLETESTI' },
  { localityId: 7418, name: 'S.LIPOVANCA' },
  { localityId: 7419, name: 'S.MINDRESTII NOI' },
  { localityId: 7421, name: 'S.COADA IAZULUI' },
  { localityId: 7423, name: 'S.SLOBOZIA-MAGURA' },
  { localityId: 7425, name: 'S.NICOLAEVCA' },
  { localityId: 7426, name: 'S.SLOBOZIA-CHISCARENI' },
  { localityId: 7428, name: 'S.BREJENI' },
  { localityId: 7430, name: 'S.ANTONOVCA' },
  { localityId: 7431, name: 'S.EVGHENIEVCA' },
  { localityId: 7432, name: 'S.GAVRILOVCA' },
  { localityId: 7434, name: 'S.PETROVCA' },
  { localityId: 7435, name: 'S.VLADIMIREUCA' },
  { localityId: 7437, name: 'S.BOBLETICI' },
  { localityId: 7438, name: 'S.FLAMINZENI' },
  { localityId: 7440, name: 'S.ALEXEUCA' },
  { localityId: 7441, name: 'S.GURA-OITUZ' },
  { localityId: 7444, name: 'S.COTOVCA' },
  { localityId: 7445, name: 'S.DOBROGEA NOUA' },
  { localityId: 7447, name: 'S.CHIRILENI' },
  { localityId: 7448, name: 'S.SACAROVCA' },
  { localityId: 7450, name: 'S.BOCANCEA-SCHIT' },
  { localityId: 7451, name: 'S.VALEA LUI VLAD' },
  { localityId: 7453, name: 'S.TRIFANESTI' },
  { localityId: 7455, name: 'S.IEZARENII NOI' },
  { localityId: 7457, name: 'S.VALEA NOROCULUI' },
  { localityId: 7458, name: 'S.MIHAILOVCA' },
  { localityId: 7459, name: 'S.PETROPAVLOVCA' },
  { localityId: 7461, name: 'S.PEPENII NOI' },
  { localityId: 7462, name: 'S.RAZALAI' },
  { localityId: 7463, name: 'S.ROMANOVCA' },
  { localityId: 7464, name: 'S.SLOVEANCA' },
  { localityId: 7466, name: 'S.CLISCAUTI' },
  { localityId: 7467, name: 'S.SESTACI' },
  { localityId: 7470, name: 'S.MARINESTI' },
  { localityId: 7472, name: 'S.TAURA NOUA' },
  { localityId: 7473, name: 'S.TAMBULA' },
  { localityId: 7474, name: 'S.OCTEABRISCOE' },
  { localityId: 7475, name: 'S.PALARIA' },
  { localityId: 8963, name: 'S.COZESTI' },
]

const SOROCA_LOCALITIES = [
  { localityId: 1930, name: 'S.NIMEREUCA' },
  { localityId: 3436, name: 'S.RUDI' },
  { localityId: 3440, name: 'S.TATARAUCA VECHE' },
  { localityId: 3450, name: 'S.VISOCA' },
  { localityId: 7801, name: 'MUN.SOROCA' },
  { localityId: 7810, name: 'S.BADICENI' },
  { localityId: 7812, name: 'S.BAXANI' },
  { localityId: 7813, name: 'S.BULBOCI' },
  { localityId: 7815, name: 'S.CAINARII VECHI' },
  { localityId: 7817, name: 'S.COSAUTI' },
  { localityId: 7819, name: 'S.CREMENCIUG' },
  { localityId: 7821, name: 'S.OCLANDA' },
  { localityId: 7824, name: 'S.DARCAUTI' },
  { localityId: 7827, name: 'S.DUBNA' },
  { localityId: 7828, name: 'S.EGORENI' },
  { localityId: 7829, name: 'S.HOLOSNITA' },
  { localityId: 7831, name: 'S.HRISTICI' },
  { localityId: 7832, name: 'S.IAROVA' },
  { localityId: 7835, name: 'S.OCOLINA' },
  { localityId: 7837, name: 'S.PARCANI' },
  { localityId: 7838, name: 'S.PIRLITA' },
  { localityId: 7841, name: 'S.RACOVAT' },
  { localityId: 7842, name: 'S.REDI-CERESNOVAT' },
  { localityId: 7843, name: 'S.REGINA MARIA' },
  { localityId: 7845, name: 'S.RUBLENITA' },
  { localityId: 7847, name: 'S.SCHINENI' },
  { localityId: 7851, name: 'S.VARANCAU' },
  { localityId: 7852, name: 'S.STOICANI' },
  { localityId: 7854, name: 'S.SEPTELICI' },
  { localityId: 7855, name: 'S.SOLCANI' },
  { localityId: 7857, name: 'S.VASILCAU' },
  { localityId: 7860, name: 'S.TRIFAUTI' },
  { localityId: 7861, name: 'S.VADENI' },
  { localityId: 7864, name: 'S.VOLOVITA' },
  { localityId: 7866, name: 'S.ZASTINCA' },
  { localityId: 1913, name: 'S.CERLINA' },
  { localityId: 3430, name: 'S.NIORCANI' },
  { localityId: 3431, name: 'S.TOLOCANESTI' },
  { localityId: 3441, name: 'S.DECEBAL' },
  { localityId: 3442, name: 'S.SLOBOZIA NOUA' },
  { localityId: 3443, name: 'S.TATARAUCA NOUA' },
  { localityId: 7811, name: 'S.GRIGORAUCA' },
  { localityId: 7814, name: 'S.BULBOCII NOI' },
  { localityId: 7816, name: 'S.FLORICENI' },
  { localityId: 7818, name: 'S.IORJNITA' },
  { localityId: 7820, name: 'S.LIVEZI' },
  { localityId: 7822, name: 'S.SOBARI' },
  { localityId: 7823, name: 'S.VALEA' },
  { localityId: 7825, name: 'S.DARCAUTII NOI' },
  { localityId: 7826, name: 'S.MALCAUTI' },
  { localityId: 7830, name: 'S.CURESNITA' },
  { localityId: 7833, name: 'S.BALINTI' },
  { localityId: 7834, name: 'S.BALINTII NOI' },
  { localityId: 7836, name: 'S.TEPILOVA' },
  { localityId: 7839, name: 'S.VANTINA' },
  { localityId: 7840, name: 'S.VANTINA MICA' },
  { localityId: 7844, name: 'S.LUGOVOE' },
  { localityId: 7846, name: 'S.RUBLENITA NOUA' },
  { localityId: 7848, name: 'S.SCHINENII NOI' },
  { localityId: 7849, name: 'S.SLOBOZIA-CREMENE' },
  { localityId: 7850, name: 'S.SLOBOZIA-VARANCAU' },
  { localityId: 7853, name: 'S.SOLONET' },
  { localityId: 7856, name: 'S.CURESNITA NOUA' },
  { localityId: 7858, name: 'S.INUNDENI' },
  { localityId: 7859, name: 'S.RUSLANOVCA' },
  { localityId: 7862, name: 'S.DUMBRAVENI' },
  { localityId: 7863, name: 'S.VOLOAVE' },
  { localityId: 7865, name: 'S.ALEXANDRU CEL BUN' },
]

const STRASENI_LOCALITIES = [
  { localityId: 6030, name: 'S.DOLNA' },
  { localityId: 6039, name: 'S.MICLEUSENI' },
  { localityId: 8001, name: 'MUN.STRASENI' },
  { localityId: 8002, name: 'OR.BUCOVATI' },
  { localityId: 8011, name: 'S.CAPRIANA' },
  { localityId: 8012, name: 'S.CHIRIANCA' },
  { localityId: 8013, name: 'S.CODREANCA' },
  { localityId: 8015, name: 'S.COJUSNA' },
  { localityId: 8016, name: 'S.GALESTI' },
  { localityId: 8018, name: 'S.GHELAUZA' },
  { localityId: 8020, name: 'S.GREBLESTI' },
  { localityId: 8022, name: 'S.LOZOVA' },
  { localityId: 8024, name: 'S.MICAUTI' },
  { localityId: 8026, name: 'S.NEGRESTI' },
  { localityId: 8027, name: 'S.ONESTI' },
  { localityId: 8028, name: 'S.PANASESTI' },
  { localityId: 8030, name: 'S.RADENI' },
  { localityId: 8032, name: 'S.ROMANESTI' },
  { localityId: 8034, name: 'S.RECEA' },
  { localityId: 8035, name: 'S.ROSCANI' },
  { localityId: 8036, name: 'S.SCORENI' },
  { localityId: 8037, name: 'S.SIRETI' },
  { localityId: 8038, name: 'S.TATARESTI' },
  { localityId: 8040, name: 'S.TIGANESTI' },
  { localityId: 8041, name: 'S.VOINOVA' },
  { localityId: 8042, name: 'S.VORNICENI' },
  { localityId: 8043, name: 'S.ZUBRESTI' },
  { localityId: 2551, name: 'S.RASSVET' },
  { localityId: 6040, name: 'S.HUZUN' },
  { localityId: 8010, name: 'S.FAGURENI' },
  { localityId: 8014, name: 'S.LUPA-RECEA' },
  { localityId: 8017, name: 'S.GALESTII NOI' },
  { localityId: 8019, name: 'S.SACA' },
  { localityId: 8021, name: 'S.MARTINESTI' },
  { localityId: 8023, name: 'S.STEJARENI' },
  { localityId: 8025, name: 'S.GORNOE' },
  { localityId: 8029, name: 'S.CIOBANCA' },
  { localityId: 8031, name: 'S.DRAGUSENI' },
  { localityId: 8033, name: 'S.ZAMCIOGI' },
]

const SOLDANESTI_LOCALITIES = [
  { localityId: 8301, name: 'OR.SOLDANESTI' },
  { localityId: 8310, name: 'S.ALCEDAR' },
  { localityId: 8313, name: 'S.CHIPESCA' },
  { localityId: 8314, name: 'S.CLIMAUTII DE JOS' },
  { localityId: 8316, name: 'S.COBILEA' },
  { localityId: 8317, name: 'S.COTIUJENII MARI' },
  { localityId: 8319, name: 'S.CUSMIRCA' },
  { localityId: 8320, name: 'S.FUZAUCA' },
  { localityId: 8321, name: 'S.GAUZENI' },
  { localityId: 8322, name: 'S.GLINJENI' },
  { localityId: 8323, name: 'S.MIHULENI' },
  { localityId: 8324, name: 'S.OLISCANI' },
  { localityId: 8325, name: 'S.PARCANI' },
  { localityId: 8326, name: 'S.POHOARNA' },
  { localityId: 8327, name: 'S.POIANA' },
  { localityId: 8328, name: 'S.RASPOPENI' },
  { localityId: 8330, name: 'S.DOBRUSA' },
  { localityId: 8332, name: 'S.ROGOJENI' },
  { localityId: 8333, name: 'S.SALCIA' },
  { localityId: 8335, name: 'S.SAMASCANI' },
  { localityId: 8336, name: 'S.SESTACI' },
  { localityId: 8337, name: 'S.SIPCA' },
  { localityId: 8338, name: 'S.VADUL-RASCOV' },
  { localityId: 8311, name: 'S.CURATURA' },
  { localityId: 8312, name: 'S.ODAIA' },
  { localityId: 8315, name: 'S.COT' },
  { localityId: 8318, name: 'S.CUSELAUCA' },
  { localityId: 8329, name: 'S.RECESTI' },
  { localityId: 8331, name: 'S.ZAHORNA' },
  { localityId: 8334, name: 'S.LELINA' },
  { localityId: 8339, name: 'S.SOCOLA' },
  { localityId: 8340, name: 'S.COBILEA LOC.ST.C.F.' },
  { localityId: 8341, name: 'ROGOJENI LOC.ST.C.F.' },
]

const STEFAN_VODA_LOCALITIES = [
  { localityId: 8501, name: 'OR.STEFAN VODA' },
  { localityId: 8510, name: 'S.ALAVA' },
  { localityId: 8512, name: 'S.ANTONESTI' },
  { localityId: 8513, name: 'S.BREZOAIA' },
  { localityId: 8514, name: 'S.CARAHASANI' },
  { localityId: 8515, name: 'S.CAPLANI' },
  { localityId: 8516, name: 'S.CIOBURCIU' },
  { localityId: 8517, name: 'S.COPCEAC' },
  { localityId: 8518, name: 'S.CROCMAZ' },
  { localityId: 8519, name: 'S.ERMOCLIA' },
  { localityId: 8520, name: 'S.FESTELITA' },
  { localityId: 8524, name: 'S.MARIANCA DE JOS' },
  { localityId: 8525, name: 'S.OLANESTI' },
  { localityId: 8526, name: 'S.PALANCA' },
  { localityId: 8527, name: 'S.POPEASCA' },
  { localityId: 8528, name: 'S.PURCARI' },
  { localityId: 8530, name: 'S.RASCAIETI' },
  { localityId: 8532, name: 'S.SEMIONOVCA' },
  { localityId: 8533, name: 'S.SLOBOZIA' },
  { localityId: 8534, name: 'S.STEFANESTI' },
  { localityId: 8535, name: 'S.TALMAZA' },
  { localityId: 8536, name: 'S.TUDORA' },
  { localityId: 8537, name: 'S.VOLINTIRI' },
  { localityId: 8511, name: 'S.LAZO' },
  { localityId: 8529, name: 'S.VIISOARA' },
  { localityId: 8531, name: 'S.RASCAIETII NOI' },
]

const TARACLIA_LOCALITIES = [
  { localityId: 8701, name: 'OR.TARACLIA' },
  { localityId: 8710, name: 'S.ALBOTA DE JOS' },
  { localityId: 8713, name: 'S.ALBOTA DE SUS' },
  { localityId: 8716, name: 'S.ALUATU' },
  { localityId: 8717, name: 'S.BALABANU' },
  { localityId: 8719, name: 'S.BUDAI' },
  { localityId: 8720, name: 'S.CAIRACLIA' },
  { localityId: 8721, name: 'S.CEALIC' },
  { localityId: 8723, name: 'S.CORTEN' },
  { localityId: 8724, name: 'S.MUSAITU' },
  { localityId: 8725, name: 'S.NOVOSIOLOVCA' },
  { localityId: 8726, name: 'S.SALCIA' },
  { localityId: 8728, name: 'OR. TVARDITA' },
  { localityId: 8729, name: 'S.VALEA PERJEI' },
  { localityId: 8730, name: 'S.VINOGRADOVCA' },
  { localityId: 8711, name: 'S.HAGICHIOI' },
  { localityId: 8712, name: 'S.HIRTOP' },
  { localityId: 8714, name: 'S.ROSITA' },
  { localityId: 8715, name: 'S.SOFIEVCA' },
  { localityId: 8722, name: 'S.SAMURZA' },
  { localityId: 8727, name: 'S.OREHOVCA' },
  { localityId: 8731, name: 'S.CHIRILOVCA' },
  { localityId: 8732, name: 'S.CIUMAI' },
  { localityId: 8733, name: 'S.MIRNOE' },
  { localityId: 8734, name: 'S.CORTENUL NOU' },
  { localityId: 8735, name: 'S.DERMENGI' },
]

const TELENESTI_LOCALITIES = [
  { localityId: 8901, name: 'OR.TELENESTI' },
  { localityId: 8912, name: 'S.BANESTI' },
  { localityId: 8914, name: 'S.BOGZESTI' },
  { localityId: 8915, name: 'S.BRINZENII NOI' },
  { localityId: 8917, name: 'S.BUDAI' },
  { localityId: 8918, name: 'S.CAZANESTI' },
  { localityId: 8921, name: 'S.CHISTELNITA' },
  { localityId: 8922, name: 'S.CHITCANII VECHI' },
  { localityId: 8924, name: 'S.CIULUCANI' },
  { localityId: 8925, name: 'S.CISLA' },
  { localityId: 8926, name: 'S.CODRUL NOU' },
  { localityId: 8927, name: 'S.COROPCENI' },
  { localityId: 8928, name: 'S.CRASNASENI' },
  { localityId: 8929, name: 'S.GHILICENI' },
  { localityId: 8932, name: 'S.HIRISENI' },
  { localityId: 8933, name: 'S.INESTI' },
  { localityId: 8934, name: 'S.LEUSENI' },
  { localityId: 8935, name: 'S.MINDRESTI' },
  { localityId: 8937, name: 'S.NEGURENI' },
  { localityId: 8940, name: 'S.NUCARENI' },
  { localityId: 8941, name: 'S.ORDASEI' },
  { localityId: 8942, name: 'S.PISTRUIENI' },
  { localityId: 8945, name: 'S.RATUS' },
  { localityId: 8950, name: 'S.SARATENII VECHI' },
  { localityId: 8952, name: 'S.SCORTENI' },
  { localityId: 8953, name: 'S.SUHULUCENI' },
  { localityId: 8955, name: 'S.TIRSITEI' },
  { localityId: 8957, name: 'S.TINTARENI' },
  { localityId: 8958, name: 'S.VASIENI' },
  { localityId: 8959, name: 'S.VEREJENI' },
  { localityId: 8960, name: 'S.ZGARDESTI' },
  { localityId: 8910, name: 'S.MIHALASA' },
  { localityId: 8911, name: 'S.MIHALASA NOUA' },
  { localityId: 8913, name: 'S.BANESTII NOI' },
  { localityId: 8916, name: 'S.BRINZENII VECHI' },
  { localityId: 8919, name: 'S.VADUL-LECA' },
  { localityId: 8920, name: 'S.VADUL-LECA NOU' },
  { localityId: 8923, name: 'S.CHITCANII NOI' },
  { localityId: 8930, name: 'S.CUCIOAIA' },
  { localityId: 8931, name: 'S.CUCIOAIA NOUA' },
  { localityId: 8936, name: 'S.CODRU' },
  { localityId: 8938, name: 'S.CHERSAC' },
  { localityId: 8939, name: 'S.DOBRUSA' },
  { localityId: 8943, name: 'S.HIRTOP' },
  { localityId: 8944, name: 'S.PISTRUIENII NOI' },
  { localityId: 8946, name: 'S.MINDRA' },
  { localityId: 8947, name: 'S.SARATENII NOI' },
  { localityId: 8948, name: 'S.ZAICANI' },
  { localityId: 8949, name: 'S.ZAICANII NOI' },
  { localityId: 8951, name: 'S.ZAHAREUCA' },
  { localityId: 8954, name: 'S.GHERMANESTI' },
  { localityId: 8956, name: 'S.FLUTURA' },
  { localityId: 8961, name: 'S.BONDAREUCA' },
  { localityId: 8962, name: 'S.CIOFU' },
]

const UNGHENI_LOCALITIES = [
  { localityId: 9201, name: 'MUN.UNGHENI' },
  { localityId: 9202, name: 'OR.CORNESTI' },
  { localityId: 9211, name: 'S.AGRONOMOVCA' },
  { localityId: 9214, name: 'S.ALEXEEVCA' },
  { localityId: 9217, name: 'S.BOGHENII NOI' },
  { localityId: 9222, name: 'S.BUCIUMENI' },
  { localityId: 9224, name: 'S.BUMBATA' },
  { localityId: 9225, name: 'S.BUSILA' },
  { localityId: 9226, name: 'S.CETIRENI' },
  { localityId: 9227, name: 'S.CHIRILENI' },
  { localityId: 9228, name: 'S.CIOROPCANI' },
  { localityId: 9231, name: 'S.CONDRATESTI' },
  { localityId: 9233, name: 'S.CORNESTI' },
  { localityId: 9234, name: 'S.CORNOVA' },
  { localityId: 9235, name: 'S.COSTULENI' },
  { localityId: 9236, name: 'S.FLORITOAIA VECHE' },
  { localityId: 9239, name: 'S.HIRCESTI' },
  { localityId: 9244, name: 'S.MACARESTI' },
  { localityId: 9246, name: 'S.MAGURELE' },
  { localityId: 9247, name: 'S.MANOILESTI' },
  { localityId: 9251, name: 'S.MORENII NOI' },
  { localityId: 9254, name: 'S.NAPADENI' },
  { localityId: 9255, name: 'S.NEGURENII VECHI' },
  { localityId: 9259, name: 'S.PETRESTI' },
  { localityId: 9261, name: 'S.PIRLITA' },
  { localityId: 9262, name: 'S.RADENII VECHI' },
  { localityId: 9263, name: 'S.SCULENI' },
  { localityId: 9267, name: 'S.SINESTI' },
  { localityId: 9269, name: 'S.TESCURENI' },
  { localityId: 9271, name: 'S.TODIRESTI' },
  { localityId: 9273, name: 'S.UNTESTI' },
  { localityId: 9274, name: 'S.VALEA MARE' },
  { localityId: 9277, name: 'S.ZAGARANCEA' },
  { localityId: 9210, name: 'S.ROMANOVCA' },
  { localityId: 9212, name: 'S.NEGURENII NOI' },
  { localityId: 9213, name: 'S.ZAZULENII NOI' },
  { localityId: 9215, name: 'S.LIDOVCA' },
  { localityId: 9216, name: 'S.SAGHIENI' },
  { localityId: 9218, name: 'S.BOGHENII VECHI' },
  { localityId: 9219, name: 'S.IZVORENI' },
  { localityId: 9220, name: 'S.MIRCESTI' },
  { localityId: 9221, name: 'S.POIANA' },
  { localityId: 9223, name: 'S.FLORESTI' },
  { localityId: 9229, name: 'S.BULHAC' },
  { localityId: 9230, name: 'S.STOLNICENI' },
  { localityId: 9232, name: 'S.CURTOAIA' },
  { localityId: 9237, name: 'S.FLORITOAIA NOUA' },
  { localityId: 9238, name: 'S.GROZASCA' },
  { localityId: 9240, name: 'S.DRUJBA' },
  { localityId: 9241, name: 'S.LEORDOAIA' },
  { localityId: 9242, name: 'S.MINZATESTI' },
  { localityId: 9243, name: 'S.VEVERITA' },
  { localityId: 9245, name: 'S.FRASINESTI' },
  { localityId: 9248, name: 'S.NOVAIA NICOLAEVCA' },
  { localityId: 9249, name: 'S.REZINA' },
  { localityId: 9250, name: 'S.VULPESTI' },
  { localityId: 9252, name: 'S.MORENII VECHI' },
  { localityId: 9253, name: 'S.SICOVAT' },
  { localityId: 9256, name: 'S.COSENI' },
  { localityId: 9257, name: 'S.TIGHIRA' },
  { localityId: 9258, name: 'S.ZAZULENII VECHI' },
  { localityId: 9260, name: 'S.MEDELENI' },
  { localityId: 9264, name: 'S.BLINDESTI' },
  { localityId: 9265, name: 'S.FLORENI' },
  { localityId: 9266, name: 'S.GHERMAN' },
  { localityId: 9268, name: 'S.POJARNA' },
  { localityId: 9270, name: 'S.HRISTOFOROVCA' },
  { localityId: 9272, name: 'S.GRASENI' },
  { localityId: 9275, name: 'S.BUZDUGANII DE JOS' },
  { localityId: 9276, name: 'S.BUZDUGANII DE SUS' },
  { localityId: 9278, name: 'S.ELIZAVETOVCA' },
  { localityId: 9279, name: 'S.SEMENI' },
  { localityId: 9280, name: 'BUCIUMENI LOC.ST.C.F.' },
  { localityId: 9281, name: 'PETRESTI LOC.ST.C.F.' },
]

const GAGAUZIA_LOCALITIES = [
  { localityId: 9601, name: 'MUN.COMRAT' },
  { localityId: 9602, name: 'MUN.CEADIR-LUNGA' },
  { localityId: 9603, name: 'OR.VULCANESTI' },
  { localityId: 9610, name: 'S.AVDARMA' },
  { localityId: 9611, name: 'S.BAURCI' },
  { localityId: 9612, name: 'S.BESALMA' },
  { localityId: 9613, name: 'S.BESGHIOZ' },
  { localityId: 9614, name: 'S.BUGEAC' },
  { localityId: 9615, name: 'S.CARBALIA' },
  { localityId: 9616, name: 'S.CAZACLIA' },
  { localityId: 9617, name: 'S.CHIOSELIA RUSA' },
  { localityId: 9618, name: 'S.CHIRIET-LUNGA' },
  { localityId: 9619, name: 'S.CHIRSOVA' },
  { localityId: 9620, name: 'S.CIOC-MAIDAN' },
  { localityId: 9621, name: 'S.CISMICHIOI' },
  { localityId: 9622, name: 'S.CONGAZ' },
  { localityId: 9624, name: 'S.CONGAZCICUL DE SUS' },
  { localityId: 9626, name: 'S.COPCEAC' },
  { localityId: 9627, name: 'S.COTOVSCOE' },
  { localityId: 9628, name: 'S.DEZGHINGEA' },
  { localityId: 9629, name: 'S.ETULIA' },
  { localityId: 9631, name: 'S.FERAPONTIEVCA' },
  { localityId: 9632, name: 'S.GAIDAR' },
  { localityId: 9633, name: 'S.JOLTAI' },
  { localityId: 9634, name: 'S.SVETLII' },
  { localityId: 9636, name: 'S.TOMAI' },
  { localityId: 9623, name: 'S.CONGAZCICUL DE JOS' },
  { localityId: 9625, name: 'S.DUDULESTI' },
  { localityId: 9630, name: 'S.ETULIA NOUA' },
  { localityId: 9635, name: 'S.ALEXEEVCA' },
  { localityId: 9637, name: 'VULCANESTI LOC.ST.C.F.' },
  { localityId: 9639, name: 'ETULIA LOC.ST.C.F.' },
]

const TDS_NISTRULUI_LOCALITIES = [
  { localityId: 700, name: 'MUN.TIRASPOL' },
  { localityId: 701, name: 'OR.DNESTROVSC' },
  { localityId: 702, name: 'OR.TIRASPOLUL NOU' },
  { localityId: 1901, name: 'OR.CAMENCA' },
  { localityId: 1911, name: 'S.CATERINOVCA' },
  { localityId: 1914, name: 'S.CRASNII OCTEABRI' },
  { localityId: 1922, name: 'S.CUZMIN' },
  { localityId: 1924, name: 'S.HRISTOVAIA' },
  { localityId: 1925, name: 'S.HRUSCA' },
  { localityId: 1931, name: 'S.OCNITA' },
  { localityId: 1932, name: 'S.PODOIMA' },
  { localityId: 1934, name: 'S.RASCOV' },
  { localityId: 1936, name: 'S.ROTARI' },
  { localityId: 1940, name: 'S.SEVERINOVCA' },
  { localityId: 1941, name: 'S.SLOBOZIA-RASCOV' },
  { localityId: 1944, name: 'S.VALEA ADINCA' },
  { localityId: 3801, name: 'OR.DUBASARI' },
  { localityId: 3812, name: 'S.COMISAROVCA NOUA' },
  { localityId: 3820, name: 'S.CRASNII VINOGRADARI' },
  { localityId: 3825, name: 'S.DOIBANI I' },
  { localityId: 3829, name: 'S.DUBAU' },
  { localityId: 3831, name: 'S.DZERJINSCOE' },
  { localityId: 3832, name: 'S.GOIAN' },
  { localityId: 3834, name: 'S.HARMATCA' },
  { localityId: 3836, name: 'S.LUNGA' },
  { localityId: 3843, name: 'S.TIBULEUCA' },
  { localityId: 5001, name: 'OR.GRIGORIOPOL' },
  { localityId: 5002, name: 'OR.MAIAC' },
  { localityId: 5011, name: 'S.BICIOC' },
  { localityId: 5013, name: 'S.BUTOR' },
  { localityId: 5015, name: 'S.CARMANOVA' },
  { localityId: 5019, name: 'S.COLOSOVA' },
  { localityId: 5022, name: 'S.CRASNOGORCA' },
  { localityId: 5023, name: 'S.DELACAU' },
  { localityId: 5025, name: 'S.HIRTOP' },
  { localityId: 5029, name: 'S.HLINAIA' },
  { localityId: 5030, name: 'S.MALAIESTI' },
  { localityId: 5032, name: 'S.SPEIA' },
  { localityId: 5033, name: 'S.SIPCA' },
  { localityId: 5035, name: 'S.TASLIC' },
  { localityId: 5036, name: 'S.TEIU' },
  { localityId: 5038, name: 'S.VINOGRADNOE' },
  { localityId: 6901, name: 'OR.RIBNITA' },
  { localityId: 6910, name: 'S.ANDREEVCA' },
  { localityId: 6913, name: 'S.BELOCI' },
  { localityId: 6914, name: 'S.BROSTENI' },
  { localityId: 6915, name: 'S.BUTUCENI' },
  { localityId: 6916, name: 'S.COBASNA' },
  { localityId: 6918, name: 'S.CRASNENCOE' },
  { localityId: 6921, name: 'S.GHIDIRIM' },
  { localityId: 6922, name: 'S.HARABA' },
  { localityId: 6923, name: 'S.HIRJAU' },
  { localityId: 6926, name: 'S.JURA' },
  { localityId: 6927, name: 'S.LENIN' },
  { localityId: 6931, name: 'S.MIHAILOVCA' },
  { localityId: 6932, name: 'S.MOCRA' },
  { localityId: 6936, name: 'S.MOLOCHISUL MARE' },
  { localityId: 6937, name: 'S.OFATINTI' },
  { localityId: 6939, name: 'S.PLOPI' },
  { localityId: 6940, name: 'S.POPENCU' },
  { localityId: 6944, name: 'S.SOVIETSCOE' },
  { localityId: 6946, name: 'S.STROIESTI' },
  { localityId: 6947, name: 'S.ULMU' },
  { localityId: 6950, name: 'S.VADUL TURCULUI' },
  { localityId: 6952, name: 'S.VARANCAU' },
  { localityId: 7601, name: 'OR.SLOBOZIA' },
  { localityId: 7602, name: 'OR.CRASNOE' },
  { localityId: 7610, name: 'S.BLIJNII HUTOR' },
  { localityId: 7611, name: 'S.CARAGAS' },
  { localityId: 7615, name: 'S.CIOBURCIU' },
  { localityId: 7617, name: 'S.COROTNA' },
  { localityId: 7618, name: 'S.FRUNZA' },
  { localityId: 7625, name: 'S.HLINAIA' },
  { localityId: 7626, name: 'S.NEZAVERTAILOVCA' },
  { localityId: 7627, name: 'S.PARCANI' },
  { localityId: 7628, name: 'S.PERVOMAISC' },
  { localityId: 7629, name: 'S.SUCLEIA' },
  { localityId: 7630, name: 'S.TIRNAUCA' },
  { localityId: 7631, name: 'S.VLADIMIROVCA' },
  { localityId: 1910, name: 'S.SOLNECINOE' },
  { localityId: 1912, name: 'S.SADCHI' },
  { localityId: 1915, name: 'S.ALEXANDROVCA' },
  { localityId: 1923, name: 'S.VOITOVCA' },
  { localityId: 1926, name: 'S.FRUNZAUCA' },
  { localityId: 1933, name: 'S.PODOIMITA' },
  { localityId: 1935, name: 'S.IANTARNOE' },
  { localityId: 1937, name: 'S.BODENI' },
  { localityId: 1938, name: 'S.SOCOLOVCA' },
  { localityId: 1945, name: 'S.CONSTANTINOVCA' },
  { localityId: 3813, name: 'S.BOSCA' },
  { localityId: 3814, name: 'S.COSNITA NOUA' },
  { localityId: 3815, name: 'S.POHREBEA NOUA' },
  { localityId: 3821, name: 'S.AFANASIEVCA' },
  { localityId: 3822, name: 'S.ALEXANDROVCA NOUA' },
  { localityId: 3823, name: 'S.CALINOVCA' },
  { localityId: 3824, name: 'S.LUNGA NOUA' },
  { localityId: 3826, name: 'S.COICOVA' },
  { localityId: 3827, name: 'S.DOIBANI II' },
  { localityId: 3830, name: 'S.GOIANUL NOU' },
  { localityId: 3833, name: 'S.IAGORLIC' },
  { localityId: 5010, name: 'S.CRASNOE' },
  { localityId: 5012, name: 'S.NOVOVLADIMIROVCA' },
  { localityId: 5014, name: 'S.INDIA' },
  { localityId: 5016, name: 'S.COTOVCA' },
  { localityId: 5017, name: 'S.FEDOSEEVCA' },
  { localityId: 5018, name: 'S.MOCEAROVCA' },
  { localityId: 5020, name: 'S.CRASNAIA BESARABIA' },
  { localityId: 5021, name: 'S.POBEDA' },
  { localityId: 5024, name: 'S.CRASNAIA GORCA' },
  { localityId: 5026, name: 'S.BRUSLACHI' },
  { localityId: 5027, name: 'S.MARIAN' },
  { localityId: 5028, name: 'S.MOCREACHI' },
  { localityId: 5031, name: 'S.CERNITA' },
  { localityId: 5034, name: 'S.VESIOLOE' },
  { localityId: 5037, name: 'S.TOCMAGIU' },
  { localityId: 6911, name: 'S.PICALOVA' },
  { localityId: 6912, name: 'S.SMALENA' },
  { localityId: 6917, name: 'S.SUHAIA RIBNITA' },
  { localityId: 6919, name: 'S.DIMITROVA' },
  { localityId: 6920, name: 'S.IVANOVCA' },
  { localityId: 6924, name: 'S.MIHAILOVCA NOUA' },
  { localityId: 6925, name: 'S.SARATEI' },
  { localityId: 6928, name: 'S.PERVOMAISC' },
  { localityId: 6929, name: 'S.POBEDA' },
  { localityId: 6930, name: 'S.STANISLAVCA' },
  { localityId: 6933, name: 'S.BASARABCA' },
  { localityId: 6934, name: 'S.SEVCENCO' },
  { localityId: 6935, name: 'S.ZAPOROJET' },
  { localityId: 6938, name: 'S.NOVAIA JIZNI' },
  { localityId: 6941, name: 'S.CHIROV' },
  { localityId: 6942, name: 'S.VLADIMIROVCA' },
  { localityId: 6943, name: 'S.ZAZULENI' },
  { localityId: 6945, name: 'S.VASILIEVCA' },
  { localityId: 6948, name: 'S.LISAIA GORA' },
  { localityId: 6949, name: 'S.ULMUL MIC' },
  { localityId: 6951, name: 'S.MOLOCHISUL MIC' },
  { localityId: 6953, name: 'S.BUSCHI' },
  { localityId: 6954, name: 'S.GHERSUNOVCA' },
  { localityId: 6955, name: 'COBASNA LOC.ST.C.F.' },
  { localityId: 7619, name: 'S.ANDRIASEVCA NOUA' },
  { localityId: 7620, name: 'S.ANDRIASEVCA VECHE' },
  { localityId: 7621, name: 'S.NOVOCOTOVSC' },
  { localityId: 7622, name: 'S.NOVOSAVITCAIA LOC.ST.C.F.' },
  { localityId: 7623, name: 'S.PRIOZIORNOE' },
  { localityId: 7624, name: 'S.UIUTNOE' },
  { localityId: 7632, name: 'S.CONSTANTINOVCA' },
  { localityId: 7633, name: 'S.NICOLSCOE' },
]

export const getAllLocalitiesOptions = () => {
  return [
    { regionId: '100', name: 'MUN.CHISINAU', value: CHISINAU_LOCALITIES },
    { regionId: '300', name: 'MUN.BALTI', value: BALTI_LOCALITIES },
    { regionId: '500', name: 'MUN.BENDER', value: BENDER_LOCALITIES },
    { regionId: '1000', name: 'R-UL ANENII NOI', value: ANENII_NOI_LOCALITIES },
    { regionId: '1200', name: 'R-UL BASARABEASCA', value: BASARABEASCA_LOCALITIES },
    { regionId: '1400', name: 'R-UL BRICENI', value: BRICENI_LOCALITIES },
    { regionId: '1700', name: 'R-UL CAHUL', value: CAHUL_LOCALITIES },
    { regionId: '2100', name: 'R-UL CANTEMIR', value: CANTEMIR_LOCALITIES },
    { regionId: '2500', name: 'R-UL CALARASI', value: CALARASI_LOCALITIES },
    { regionId: '2700', name: 'R-UL CAUSENI', value: CAUSENI_LOCALITIES },
    { regionId: '2900', name: 'R-UL CIMISLIA', value: CIMISLIA_LOCALITIES },
    { regionId: '3100', name: 'R-UL CRIULENI', value: CRIULENI_LOCALITIES },
    { regionId: '3400', name: 'R-UL DONDUSENI', value: DONDUSENI_LOCALITIES },
    { regionId: '3600', name: 'R-UL DROCHIA', value: DROCHIA_LOCALITIES },
    { regionId: '3800', name: 'R-UL DUBASARI', value: DUBASARI_LOCALITIES },
    { regionId: '4100', name: 'R-UL EDINET', value: EDINET_LOCALITIES },
    { regionId: '4300', name: 'R-UL FALESTI', value: FALESTI_LOCALITIES },
    { regionId: '4500', name: 'R-UL FLORESTI', value: FLORESTI_LOCALITIES },
    { regionId: '4800', name: 'R-UL GLODENI', value: GLODENI_LOCALITIES },
    { regionId: '5300', name: 'R-UL HINCESTI', value: HINCESTI_LOCALITIES },
    { regionId: '5500', name: 'R-UL IALOVENI', value: IALOVENI_LOCALITIES },
    { regionId: '5700', name: 'R-UL LEOVA', value: LEOVA_LOCALITIES },
    { regionId: '6000', name: 'R-UL NISPORENI', value: NISPORENI_LOCALITIES },
    { regionId: '6200', name: 'R-UL OCNITA', value: OCNITA_LOCALITIES },
    { regionId: '6400', name: 'R-UL ORHEI', value: ORHEI_LOCALITIES },
    { regionId: '6700', name: 'R-UL REZINA', value: REZINA_LOCALITIES },
    { regionId: '7100', name: 'R-UL RISCANI', value: RISCANI_LOCALITIES },
    { regionId: '7400', name: 'R-UL SINGEREI', value: SINGEREI_LOCALITIES },
    { regionId: '7800', name: 'R-UL SOROCA', value: SOROCA_LOCALITIES },
    { regionId: '8000', name: 'R-UL STRASENI', value: STRASENI_LOCALITIES },
    { regionId: '8300', name: 'R-UL SOLDANESTI', value: SOLDANESTI_LOCALITIES },
    { regionId: '8500', name: 'R-UL STEFAN VODA', value: STEFAN_VODA_LOCALITIES },
    { regionId: '8700', name: 'R-UL TARACLIA', value: TARACLIA_LOCALITIES },
    { regionId: '8900', name: 'R-UL TELENESTI', value: TELENESTI_LOCALITIES },
    { regionId: '9200', name: 'R-UL UNGHENI', value: UNGHENI_LOCALITIES },
    { regionId: '9600', name: 'GAGAUZIA', value: GAGAUZIA_LOCALITIES },
    { regionId: '9800', name: 'TDS NISTRULUI', value: TDS_NISTRULUI_LOCALITIES },
  ]
}
