export const regions = [
  'MUN.CHISINAU',
  'MUN.BALTI',
  'MUN.BENDER',
  'R-UL ANENII NOI',
  'R-UL BASARABEASCA',
  'R-UL BRICENI',
  'R-UL CAHUL',
  'R-UL CANTEMIR',
  'R-UL CALARASI',
  'R-UL CAUSENI',
  'R-UL CIMISLIA',
  'R-UL CRIULENI',
  'R-UL DONDUSENI',
  'R-UL DROCHIA',
  'R-UL DUBASARI',
  'R-UL EDINET',
  'R-UL FALESTI',
  'R-UL FLORESTI',
  'R-UL GLODENI',
  'R-UL HINCESTI',
  'R-UL IALOVENI',
  'R-UL LEOVA',
  'R-UL NISPORENI',
  'R-UL OCNITA',
  'R-UL ORHEI',
  'R-UL REZINA',
  'R-UL RISCANI',
  'R-UL SINGEREI',
  'R-UL SOROCA',
  'R-UL STRASENI',
  'R-UL SOLDANESTI',
  'R-UL STEFAN VODA',
  'R-UL TARACLIA',
  'R-UL TELENESTI',
  'R-UL UNGHENI',
  'GAGAUZIA',
  'TDS NISTRULUI',
]

export const localities = [
  {
    region: 'MUN.CHISINAU',
    options: [
      'SEC.BOTANICA',
      'SEC.BUIUCANI',
      'SEC.CENTRU',
      'SEC.CIOCANA',
      'SEC.RISCANI',
      'OR.SINGERA',
      'S.DOBROGEA',
      'S.REVACA',
      'OR.DURLESTI',
      'OR.VATRA',
      'S.CONDRITA',
      'S.GHIDIGHICI',
      'OR.CODRU',
      'OR.VADUL LUI VODA',
      'S.BUBUIECI',
      'S.BIC',
      'S.CRUZESTI',
      'S.CEROBORTA',
      'S.TOHATIN',
      'S.BUNETI',
      'S.CHELTUITORI',
      'S.COLONITA',
      'OR.CRICOVA',
      'S.CIORESCU',
      'S.FAURESTI',
      'S.GOIAN',
      'S.GRATIESTI',
      'S.HULBOACA',
      'S.HUMULESTI',
      'S.BUDESTI',
      'S.VADULENI',
      'S.STAUCENI',
      'S.GOIANUL NOU',
      'S.BACIOI',
      'S.FRUMUSICA',
      'S.STRAISTENI',
      'S.BRAILA',
      'S.TRUSENI',
    ],
  },
  {
    region: 'MUN.BALTI',
    options: ['MUN.BALTI', 'S.ELIZAVETA', 'S.SADOVOE'],
  },
  {
    region: 'MUN.BENDER',
    options: ['MUN.BENDER', 'S.PROTEAGAILOVCA'],
  },
  {
    region: 'R-UL ANENII NOI',
    options: [
      'S.VARNITA',
      'OR.ANENII NOI',
      'S.BOTNARESTI',
      'S.BULBOACA',
      'S.CALFA',
      'S.CHETROSU',
      'S.CHIRCA',
      'S.CIOBANOVCA',
      'S.COBUSCA NOUA',
      'S.COBUSCA VECHE',
      'S.DELACAU',
      'S.FLORENI',
      'S.GEAMANA',
      'S.GURA BICULUI',
      'S.HIRBOVAT',
      'S.MAXIMOVCA',
      'S.MERENI',
      'S.MERENII NOI',
      'S.PUHACENI',
      'S.ROSCANI',
      'S.SPEIA',
      'S.SERPENI',
      'S.TELITA',
      'S.TINTARENI',
      'S.OCHIUL ROS',
      'S.BERIOZCHI',
      'S.HIRBOVATUL NOU',
      'S.SALCIA',
      'S.CALFA NOUA',
      'S.BOTNARESTII NOI',
      'S.SOCOLENI',
      'S.FLORESTI',
      'S.CRETOAIA',
      'S.BATIC',
      'S.RUSENI',
      'S.ALBINITA',
      'S.TELITA NOUA',
      'S.TODIRESTI',
      'S.TROITA NOUA',
      'S.BALMAZ',
      'S.MIRNOE',
      'S.PICUS',
      'S.ZOLOTIEVCA',
      'S.LARGA',
      'S.NICOLAEVCA',
    ],
  },
  {
    region: 'R-UL BASARABEASCA',
    options: [
      'OR.BASARABEASCA',
      'S.ABACLIA',
      'S.BASCALIA',
      'S.CARABETOVCA',
      'S.IORDANOVCA',
      'S.ISERLIA',
      'S.SADACLIA',
      'S.BOGDANOVCA',
      'S.CARABIBER',
      'S.IVANOVCA',
    ],
  },
  {
    region: 'R-UL BRICENI',
    options: [
      'OR.BRICENI',
      'OR.LIPCANI',
      'S.BALASINESTI',
      'S.BALCAUTI',
      'S.BERLINTI',
      'S.BOGDANESTI',
      'S.BULBOACA',
      'S.CARACUSENII VECHI',
      'S.COLICAUTI',
      'S.CORJEUTI',
      'S.COTEALA',
      'S.COTIUJENI',
      'S.CRIVA',
      'S.DREPCAUTI',
      'S.BELEAVINTI',
      'S.GRIMANCAUTI',
      'S.HALAHORA DE SUS',
      'S.HLINA',
      'S.LARGA',
      'S.MARCAUTI',
      'S.MEDVEJA',
      'S.MIHAILENI',
      'S.PERERITA',
      'S.SIRAUTI',
      'S.SLOBOZIA-SIRAUTI',
      'S.TABANI',
      'S.TETCANI',
      'S.TREBISAUTI',
      'S.BOCICAUTI',
      'S.BEZEDA',
      'S.GRIMESTI',
      'S.CARACUSENII NOI',
      'S.TRESTIENI',
      'S.CHIRILOVCA',
      'S.HALAHORA DE JOS',
      'S.PAVLOVCA',
      'S.MARCAUTII NOI',
      'S.SLOBOZIA-MEDVEJA',
      'S.GROZNITA',
    ],
  },
  {
    region: 'R-UL CAHUL',
    options: [
      'MUN.CAHUL',
      'S.ANDRUSUL DE JOS',
      'S.ANDRUSUL DE SUS',
      'S.BADICUL MOLDOVENESC',
      'S.BAURCI-MOLDOVENI',
      'S.BUCURIA',
      'S.BURLACU',
      'S.CHIOSELIA MARE',
      'S.CRIHANA VECHE',
      'S.CUCOARA',
      'S.HULUBOAIA',
      'S.LARGA NOUA',
      'S.LEBEDENCO',
      'S.LOPATICA',
      'S.LUCESTI',
      'S.MANTA',
      'S.MOSCOVEI',
      'S.PELINEI',
      'S.ROSU',
      'S.TARACLIA DE SALCIE',
      'S.TARTAUL DE SALCIE',
      'S.TATARESTI',
      'S.ZIRNESTI',
      'S.DOINA',
      'S.BORCEAG',
      'S.ALEXANDRU IOAN CUZA',
      'S.BRINZA',
      'S.BURLACENI',
      'S.ALEXANDERFELD',
      'S.CISLITA-PRUT',
      'S.COLIBASI',
      'S.GAVANOASA',
      'S.GIURGIULESTI',
      'S.IUJNOE',
      'S.SLOBOZIA MARE',
      'S.VADUL LUI ISAC',
      'S.VALENI',
      'S.TUDORESTI',
      'S.SPICOASA',
      'S.COTIHANA',
      'S.CHIRCANI',
      'S.FRUMUSICA',
      'S.LARGA VECHE',
      'S.HUTULU',
      'S.URSOAIA',
      'S.PASCANI',
      'S.TRIFESTII NOI',
      'S.SATUC',
      'S.PAICU',
      'S.TRETESTI',
      'S.IASNAIA POLEANA',
      'S.RUMEANTEV',
      'S.GRECENI',
      'S.NICOLAEVCA',
      'S.VLADIMIROVCA',
    ],
  },
  {
    region: 'R-UL CANTEMIR',
    options: [
      'OR.CANTEMIR',
      'S.ANTONESTI',
      'S.BAIMACLIA',
      'S.CANIA',
      'S.CAPACLIA',
      'S.CHIOSELIA',
      'S.CIOBALACCIA',
      'S.CIIETU',
      'S.CIRPESTI',
      'S.CISLA',
      'S.COCIULIA',
      'S.COSTANGALIA',
      'S.ENICHIOI',
      'S.GOTESTI',
      'S.HARAGIS',
      'S.LARGUTA',
      'S.LINGURA',
      'S.PLESENI',
      'S.PLOPI',
      'S.PORUMBESTI',
      'S.SADIC',
      'S.STOIANOVCA',
      'S.SAMALIA',
      'S.TARTAUL',
      'S.TOCENI',
      'S.TIGANCA',
      'S.VISNIOVCA',
      'S.LECA',
      'S.ACUI',
      'S.IEPURENI',
      'S.TARANCUTA',
      'S.FLOCOASA',
      'S.VICTOROVCA',
      'S.DIMITROVA',
      'S.SUHAT',
      'S.SOFRANOVCA',
      'S.BOBOCICA',
      'S.FLORICICA',
      'S.TOLICA',
      'S.CRACIUN',
      'S.POPOVCA',
      'S.HANASENI',
      'S.TATARASENI',
      'S.ALEXANDROVCA',
      'S.HIRTOP',
      'S.TARACLIA (com. Plopi)',
      'S.CONSTANTINESTI',
      'S.TARACLIA (com. Sadic)',
      'S.GHIOLTOSU',
      'S.TIGANCA NOUA',
      'S.VILCELE',
    ],
  },
  {
    region: 'R-UL CALARASI',
    options: [
      'OR.CALARASI',
      'S.BAHMUT',
      'S.BRAVICEA',
      'S.BUDA',
      'S.CABAIESTI',
      'S.DERENEU',
      'S.FRUMOASA',
      'S.HIROVA',
      'S.HIRJAUCA',
      'S.HOGINESTI',
      'S.HORODISTE',
      'S.MELESENI',
      'S.NISCANI',
      'S.ONISCANI',
      'S.PAULESTI',
      'S.PITUSCA',
      'S.PIRJOLTENI',
      'S.RACIULA',
      'S.RADENI',
      'S.SADOVA',
      'S.SASENI',
      'S.SIPOTENI',
      'S.TEMELEUTI',
      'S.TUZARA',
      'S.PETICENI',
      'S.TIBIRICA',
      'S.VALCINET',
      'S.VARZARESTII NOI',
      'S.ORICOVA',
      'S.BAHU',
      'S.URSARI',
      'S.BULARDA',
      'S.DUMA',
      'S.LEORDOAIA',
      'S.MINDRA',
      'S.PALANCA',
      'S.HIRBOVAT',
      'S.SVERIDA',
      'S.PARCANI',
      'S.PODUL LUNG',
      'S.NOVACI',
      'S.SELISTEA NOUA',
      'BAHMUT LOC.C.F.',
      'S.SCHINOASA',
    ],
  },
  {
    region: 'R-UL CAUSENI',
    options: [
      'S.CREMENCIUG',
      'OR.CAINARI',
      'S.BAIMACLIA',
      'S.CHIRCAIESTII NOI',
      'S.CIUFLESTI',
      'S.CIRNATENII NOI',
      'S.COSCALIA',
      'S.PERVOMAISC',
      'S.TARACLIA',
      'OR.CAUSENI',
      'S.BACCEALIA',
      'S.CHIRCAIESTI',
      'S.CIRNATENI',
      'S.FIRLADENI',
      'S.GISCA',
      'S.GRIGORIEVCA',
      'S.HAGIMUS',
      'S.OPACI',
      'S.PLOPI-STIUBEI',
      'S.SAITI',
      'S.SALCUTA',
      'S.TANATARI',
      'S.TANATARII NOI',
      'S.TOCUZ',
      'S.UCRAINCA',
      'S.URSOAIA',
      'S.ZAIM',
      'S.CHITCANI',
      'S.COPANCA',
      'S.GRADINITA',
      'S.SURCHICENI',
      'S.BAURCI',
      'S.SALCUTA NOUA',
      'S.CONSTANTINOVCA',
      'S.PLOP',
      'CAINARI LOC.C.F.',
      'S.TRICOLICI',
      'S.FIRLADENII NOI',
      'S.STEFANESTI',
      'S.URSOAIA NOUA',
      'S.ZVIOZDOCICA',
      'S.MARIANCA DE SUS',
      'ZAIM LOC.C.F.',
      'S.MERENESTI',
      'S.ZAHORNA',
      'S.LEUNTEA',
      'S.VALEA VERDE',
    ],
  },
  {
    region: 'R-UL CIMISLIA',
    options: [
      'S.TROITCOE',
      'S.BATIR',
      'S.CODRENI',
      'OR.CIMISLIA',
      'S.ALBINA',
      'S.CENAC',
      'S.CIUCUR-MINGIR',
      'S.ECATERINOVCA',
      'S.GRADISTE',
      'S.GURA GALBENEI',
      'S.HIRTOP',
      'S.IALPUGENI',
      'S.PORUMBREI',
      'S.IVANOVCA NOUA',
      'S.JAVGUR',
      'S.LIPOVENI',
      'S.MIHAILOVCA',
      'S.SAGAIDAC',
      'S.SATUL NOU',
      'S.SELEMET',
      'S.SURIC',
      'S.TOPALA',
      'S.VALEA PERJEI',
      'S.SAGAIDACUL NOU',
      'S.ZLOTI LOC.ST.CF.',
      'S.FETITA',
      'S.BOGDANOVCA NOUA',
      'S.BOGDANOVCA VECHE',
      'S.COSTANGALIA',
      'S.IALPUG',
      'S.PRISACA',
      'S.MARIENFELD',
      'S.IURIEVCA',
      'S.ARTIMONOVCA',
      'S.MAXIMENI',
      'S.MUNTENI',
      'S.SCHINOSICA',
      'S.MERENI',
      'S.DIMITROVCA',
    ],
  },
  {
    region: 'R-UL CRIULENI',
    options: [
      'OR.CRIULENI',
      'S.BALABANESTI',
      'S.BALTATA',
      'S.BOSCANA',
      'S.CIMISENI',
      'S.CORJOVA',
      'S.COSERNITA',
      'S.CRUGLIC',
      'S.DOLINNOE',
      'S.DRASLICENI',
      'S.MAGDACESTI',
      'S.DUBASARII VECHI',
      'S.HIRTOPUL MARE',
      'S.HRUSOVA',
      'S.ISNOVAT',
      'S.IZBISTE',
      'S.JEVRENI',
      'S.MASCAUTI',
      'S.MICLESTI',
      'S.ONITCANI',
      'S.PASCANI',
      'S.RACULESTI',
      'S.RISCOVA',
      'S.SLOBOZIA-DUSCA',
      'S.ZAICANA',
      'S.ZOLONCENI',
      'S.MALAIESTI',
      'S.MALAIESTII NOI',
      'S.BALTATA DE SUS',
      'S.SAGAIDAC',
      'S.SAGAIDACUL DE SUS',
      'S.MARDAREUCA',
      'S.VALEA COLONITEI',
      'S.VALEA SATULUI',
      'S.LOGANESTI',
      'S.RATUS',
      'S.HIRTOPUL MIC',
      'S.CHETROASA',
      'S.CIOPLENI',
      'S.STETCANI',
      'S.OHRINCEA',
      'S.PORUMBENI',
      'S.BALASESTI',
    ],
  },
  {
    region: 'R-UL DONDUSENI',
    options: [
      'OR.DONDUSENI',
      'S.ARIONESTI',
      'S.BARABOI',
      'S.BRICENI',
      'S.CERNOLEUCA',
      'S.CLIMAUTI',
      'S.CORBU',
      'S.CRISCAUTI',
      'S.DONDUSENI',
      'S.ELIZAVETOVCA',
      'S.FRASIN',
      'S.HORODISTE',
      'S.MOSANA',
      'S.PIVNICENI',
      'S.PLOP',
      'S.POCROVCA',
      'S.REDIUL MARE',
      'S.SCAIENI',
      'S.SUDARCA',
      'S.TELESEUCA',
      'S.TIRNOVA',
      'S.TAUL',
      'S.BOROSENI',
      'S.CARAIMAN',
      'S.CODRENII NOI',
      'S.OCTEABRISCOE',
      'S.BRAICAU',
      'S.TELESEUCA NOUA',
      'S.BRICEVA',
      'S.ELENOVCA',
    ],
  },
  {
    region: 'R-UL DROCHIA',
    options: [
      'S.FINTINITA',
      'S.MARAMONOVCA',
      'S.MINDIC',
      'OR.DROCHIA',
      'S.ANTONEUCA',
      'S.BARONCEA',
      'S.CHETROSU',
      'S.COTOVA',
      'S.DOMINTENI',
      'S.DROCHIA',
      'S.GRIBOVA',
      'S.HASNASENII MARI',
      'S.HASNASENII NOI',
      'S.MICIURIN',
      'S.MOARA DE PIATRA',
      'S.NICORENI',
      'S.OCHIUL ALB',
      'S.PALANCA',
      'S.PERVOMAISCOE',
      'S.PETRENI',
      'S.POPESTII DE JOS',
      'S.POPESTII DE SUS',
      'S.SOFIA',
      'S.SALVIRII VECHI',
      'S.SURI',
      'S.TARIGRAD',
      'S.ZGURITA',
      'S.PELINIA',
      'GHIZDITA LOC.C.F.',
      'S.SERGHEUCA',
      'S.BARONCEA NOUA',
      'S.MACAREUCA',
      'S.LAZO',
      'S.HOLOSNITA NOUA',
      'S.SALVIRII NOI',
      'S.POPESTII NOI',
      'S.CEAPAEVCA',
      'S.ILICIOVCA',
      'S.SURII NOI',
      'PELINIA LOC.C.F.',
    ],
  },
  {
    region: 'R-UL DUBASARI',
    options: [
      'S.COCIERI',
      'S.CORJOVA',
      'S.COSNITA',
      'S.DOROTCAIA',
      'S.HOLERCANI',
      'S.MARCAUTI',
      'S.MOLOVATA',
      'S.MOLOVATA NOUA',
      'S.OXENTEA',
      'S.PIRITA',
      'S.USTIA',
      'S.VASILIEVCA',
      'S.MAHALA',
      'S.POHREBEA',
      'S.ROGHI',
    ],
  },
  {
    region: 'R-UL EDINET',
    options: [
      'MUN.EDINET',
      'OR.CUPCINI',
      'S.BLESTENI',
      'S.BRATUSENI',
      'S.BRINZENI',
      'S.BADRAGII NOI',
      'S.BADRAGII VECHI',
      'S.BURLANESTI',
      'S.CHETROSICA NOUA',
      'S.CORPACI',
      'S.CUCONESTII NOI',
      'S.FETESTI',
      'S.GASPAR',
      'S.GOLENI',
      'S.GORDINESTI',
      'S.HANCAUTI',
      'S.HINCAUTI',
      'S.HLINAIA',
      'S.LOPATNIC',
      'S.PARCOVA',
      'S.ROTUNDA',
      'S.RUSENI',
      'S.STOLNICENI',
      'S.SOFRINCANI',
      'S.TEREBNA',
      'S.TIRNOVA',
      'S.TRINCA',
      'S.CONSTANTINOVCA',
      'S.VIISOARA',
      'S.ZABRICENI',
      'S.ALEXEEVCA',
      'S.CEPELEUTI',
      'S.CHETROSICA VECHE',
      'S.ALEXANDRENI',
      'S.VOLODENI',
      'S.BRATUSENII NOI',
      'S.BUZDUGENI',
      'S.CHIURT',
      'S.CUCONESTII VECHI',
      'S.CLISCAUTI',
      'S.POIANA',
      'S.GORDINESTII NOI',
      'S.FINTINA ALBA',
      'S.HLINAIA MICA',
      'S.SLOBODCA',
      'S.IACHIMENI',
      'S.ONESTI',
      'S.RINGACI',
      'S.VANCICAUTI',
    ],
  },
  {
    region: 'R-UL FALESTI',
    options: [
      'OR.FALESTI',
      'S.ALBINETUL VECHI',
      'S.BOCANI',
      'S.CALINESTI',
      'S.CHETRIS',
      'S.HINCESTI',
      'S.CALUGAR',
      'S.CIOLACU NOU',
      'S.EGOROVCA',
      'S.FALESTII NOI',
      'S.GLINJENI',
      'S.HILIUTI',
      'S.HORESTI',
      'S.ILENUTA',
      'S.ISCALAU',
      'S.CATRANIC',
      'S.IZVOARE',
      'S.LOGOFTENI',
      'S.MARANDENI',
      'S.MUSTEATA',
      'S.NATALIEVCA',
      'S.NAVIRNET',
      'S.OBREJA VECHE',
      'S.PIETROSU',
      'S.PINZARENI',
      'S.PIRLITA',
      'S.POMPA',
      'S.PRUTENI',
      'S.RAUTEL',
      'S.RISIPENI',
      'S.SARATA VECHE',
      'S.SCUMPIA',
      'S.TAXOBENI',
      'S.ALBINETUL NOU',
      'S.REDIUL DE JOS',
      'S.REDIUL DE SUS',
      'S.CHETRISUL NOU',
      'S.FRUMUSICA',
      'S.SOCII NOI',
      'S.SOCII VECHI',
      'S.CIOLACU VECHI',
      'S.FAGADAU',
      'S.POCROVCA',
      'S.SOLT╨₧AIA',
      'S.CIULUC',
      'S.PIETROSUL NOU',
      'S.RAUTELUL NOU',
      'S.LUCACENI',
      'S.UNTENI',
      'S.BURGHELEA',
      'S.DOLTU',
      'S.BELEUTI',
      'S.COMAROVCA',
      'S.IVANOVCA',
      'S.POPOVCA',
      'S.TAPOC',
      'S.OBREJA NOUA',
      'S.MAGURA',
      'S.MAGURA NOUA',
      'S.MOLDOVEANCA',
      'S.PINZARENII NOI',
      'S.PERVOMAISC',
      'S.SUVOROVCA',
      'S.CUZMENII VECHI',
      'S.DRUJINENI',
      'S.VALEA RUSULUI',
      'S.BOCSA',
      'S.HITRESTI',
      'S.SARATA NOUA',
      'S.HIRTOP',
      'S.MAGUREANCA',
      'S.NICOLAEVCA',
      'S.HRUBNA NOUA',
      'S VRANESTI',
      'S.CATRANIC LOC.ST.C.F.',
      'FABRICA DE ZAHAR',
    ],
  },
  {
    region: 'R-UL FLORESTI',
    options: [
      'S.CUHURESTII DE JOS',
      'S.CUHURESTII DE SUS',
      'S.CUNICEA',
      'S.JAPCA',
      'S.NAPADOVA',
      'S.SANATAUCA',
      'S.TEMELEUTI',
      'S.TIRGUL-VERTIUJENI',
      'S.VASCAUTI',
      'S.VERTIUJENI',
      'S.ZALUCENI',
      'OR.FLORESTI',
      'OR.GHINDESTI',
      'OR.MARCULESTI',
      'S.ALEXEEVCA',
      'S.BAHRINESTI',
      'S.CASUNCA',
      'S.CERNITA',
      'S.CIRIPCAU',
      'S.CIUTULESTI',
      'S.COSERNITA',
      'S.DOMULGENI',
      'S.FRUMUSICA',
      'S.GHINDESTI',
      'S.GURA CAMENCII',
      'S.GURA CAINARULUI',
      'S.ILICIOVCA',
      'S.IZVOARE',
      'S.LUNGA',
      'S.MARCULESTI',
      'S.NICOLAEVCA',
      'S.PRAJILA',
      'S.PRODANESTI',
      'S.PUTINESTI',
      'S.RADULENII VECHI',
      'S.ROSIETICI',
      'S.SEVIROVA',
      'S.STEFANESTI',
      'S.TRIFANESTI',
      'S.VARVAREUCA',
      'S.TIPORDEI',
      'S.NICOLAEVCA',
      'S.UNCHITESTI',
      'S.BURSUC',
      'S.FAGADAU',
      'S.OCTEABRISCOE',
      'UNCHITESTI LOC.C.F.',
      'S.CHIRILOVCA',
      'S.DUMITRENI',
      'S.RADULENII NOI',
      'S.ION VODA',
      'S.MARINESTI',
      'S.SIRBESTI',
      'S.FRUMUSICA NOUA',
      'S.HIRTOP',
      'S.TIRA',
      'S.BOBULESTI',
      'S.GVOZDOVA',
      'S.ZAROJENI',
      'S.MAISCOE',
      'S.BEZENI',
      'S.SCAIENI',
      'S.VALEA RADOAIEI',
      'S.ANTONOVCA',
      'S.FRUNZESTI',
      'S.MIHAILOVCA',
      'S.CAPRESTI',
      'S.CENUSA',
      'S.ROSIETICII VECHI',
      'S.IVANOVCA',
      'S.PRODANESTII VECHI',
      'S.ALEXANDROVCA',
      'S.STIRCENI',
      'TIRA LOC.C.F.',
    ],
  },
  {
    region: 'R-UL GLODENI',
    options: [
      'OR.GLODENI',
      'S.BALATINA',
      'S.CAJBA',
      'S.CAMENCA',
      'S.CIUCIULEA',
      'S.COBANI',
      'S.CUHNESTI',
      'S.DANU',
      'S.DUSMANI',
      'S.FUNDURII NOI',
      'S.FUNDURII VECHI',
      'S.HIJDIENI',
      'S.IABLOANA',
      'S.LIMBENII NOI',
      'S.LIMBENII VECHI',
      'S.PETRUNEA',
      'S.STURZOVCA',
      'S.USTIA',
      'S.VIISOARA',
      'S.STIRCEA',
      'S.CLOCOCENII VECHI',
      'S.LIPOVAT',
      'S.TOMESTII NOI',
      'S.TOMESTII VECHI',
      'S.BRINZENI',
      'S.BUTESTI',
      'S.MOLESTI',
      'S.BISERICANI',
      'S.COT',
      'S.SERGHIENI',
      'S.CAMENCUTA',
      'S.NICOLAEVCA',
      'S.SOROCA',
      'S.MOARA DOMNEASCA',
      'S.MOVILENI',
    ],
  },
  {
    region: 'R-UL HINCESTI',
    options: [
      'MUN.HINCESTI',
      'S.BALCEANA',
      'S.BOBEICA',
      'S.BOGHICENI',
      'S.BOZIENI',
      'S.BUJOR',
      'S.BUTENI',
      'S.CARACUI',
      'S.CALMATUI',
      'S.CARPINENI',
      'S.CIOARA',
      'S.COTUL MORII',
      'S.CRASNOARMEISCOE',
      'S.DANCU',
      'S.FIRLADENI',
      'S.FUNDUL GALBENEI',
      'S.IVANOVCA',
      'S.LAPUSNA',
      'S.LEUSENI',
      'S.LOGANESTI',
      'S.MERESENI',
      'S.MINGIR',
      'S.MIRESTI',
      'S.NEGREA',
      'S.NEMTENI',
      'S.OBILENI',
      'S.ONESTI',
      'S.PASCANI',
      'S.PERVOMAISCOE',
      'S.POGANESTI',
      'S.SARATA-GALBENA',
      'S.SECARENI',
      'S.SOFIA',
      'S.STOLNICENI',
      'S.SIPOTENI',
      'S.VOINESCU',
      'S.CATELENI',
      'S.CIUCIULENI',
      'S.DRAGUSENII NOI',
      'S.DAHNOVICI',
      'S.DRAGUSENI',
      'S.DUBOVCA',
      'S.CARPINEANCA',
      'S.COROLIOVCA',
      'S.VALEA FLORII',
      'S.HORJESTI',
      'S.TALAIESTI',
      'S.COSTESTI',
      'S.FRASIN',
      'S.SARATENI',
      'S.ANINI',
      'S.RUSCA',
      'S.FETEASCA',
      'S.SARATA-MERESENI',
      'S.SEMIONOVCA',
      'S.CHETROSENI',
      'S.STRIMBENI',
      'S.PERENI',
      'S.MARCHET',
      'S.BRATIANOVCA',
      'S.CORNESTI',
      'S.SECARENII NOI',
      'S.HORODCA',
    ],
  },
  {
    region: 'R-UL IALOVENI',
    options: [
      'OR.IALOVENI',
      'S.CARBUNA',
      'S.CIGIRLENI',
      'S.GANGURA',
      'S.RAZENI',
      'S.VARATIC',
      'S.BARDAR',
      'S.COSTESTI',
      'S.DANCENI',
      'S.HANSCA',
      'S.HORESTI',
      'S.HORODCA',
      'S.MALCOCI',
      'S.MILESTII MICI',
      'S.MOLESTI',
      'S.NIMORENI',
      'S.POJARENI',
      'S.PUHOI',
      'S.RUSESTII NOI',
      'S.SOCITENI',
      'S.SURUCENI',
      'S.TIPALA',
      'S.ULMU',
      'S.VASIENI',
      'S.ZIMBRENI',
      'S.ALEXANDROVCA',
      'S.HOMUTEANOVCA',
      'S.MISOVCA',
      'S.MILESTII NOI',
      'S.PIATRA ALBA',
      'S.RUSESTII VECHI',
      'S.BALTATI',
      'S.BUDAI',
      'S.GAURENI',
    ],
  },
  {
    region: 'R-UL LEOVA',
    options: [
      'OR.LEOVA',
      'OR.IARGARA',
      'S.BAIUS',
      'S.BESTEMAC',
      'S.BOROGANI',
      'S.CAZANGIC',
      'S.CEADIR',
      'S.CNEAZEVCA',
      'S.COLIBABOVCA',
      'S.COVURLUI',
      'S.CUPCUI',
      'S.FILIPENI',
      'S.ROMANOVCA',
      'S.HANASENII NOI',
      'S.ORAC',
      'S.SARATA NOUA',
      'S.SARATA-RAZESI',
      'S.SARATENI',
      'S.SARATICA NOUA',
      'S.SIRMA',
      'S.TIGHECI',
      'S.TOCHILE-RADUCANI',
      'S.TOMAI',
      'S.TOMAIUL NOU',
      'S.MESENI',
      'S.COCIULIA NOUA',
      'S.HIRTOP',
      'S.PITESTI',
      'S.FRUMUSICA',
      'S.SELISTE',
      'S.CIZLAR',
      'S.NICOLAEVCA',
      'S.VICTORIA',
      'S.CIMPUL DREPT',
      'S.CUPORANI',
      'S.SARATICA VECHE',
      'S.VOZNESENI',
      'S.TROIAN',
      'S.TROITA',
      'S. BULGÉRICA',
    ],
  },
  {
    region: 'R-UL NISPORENI',
    options: [
      'OR.NISPORENI',
      'S.BALANESTI',
      'S.BALAURESTI',
      'S.BARBOIENI',
      'S.BOLDURESTI',
      'S.BOLTUN',
      'S.BRATULENI',
      'S.BURSUC',
      'S.CALIMANESTI',
      'S.CIORESTI',
      'S.CIUTESTI',
      'S.CRISTESTI',
      'S.GROZESTI',
      'S.IURCENI',
      'S.MARINICI',
      'S.MILESTI',
      'S.SELISTE',
      'S.SOLTANESTI',
      'S.SISCANI',
      'S.VALEA-TRESTIENI',
      'S.VARZARESTI',
      'S.VINATORI',
      'S.ZBEROAIA',
      'S.GAURENI',
      'S.BACSENI',
      'S.CHILISOAIA',
      'S.CIRNESTI',
      'S.VULCANESTI',
      'S.VALEA NIRNOVEI',
      'S.DROJDIENI',
      'S.MIRZOAIA',
      'S.HELESTENI',
      'S.PARUCENI',
      'S.ODAIA',
      'S.ISAICANI',
      'S.LUMINITA',
      'S.ODOBESTI',
      'S.SELISTENI',
      'S.SENDRENI',
    ],
  },
  {
    region: 'R-UL OCNITA',
    options: [
      'OR.OCNITA',
      'OR.FRUNZA',
      'OR.OTACI',
      'S.BIRLADENI',
      'S.BIRNOVA',
      'S.CALARASOVCA',
      'S.CLOCUSNA',
      'S.CORESTAUTI',
      'S.DINGENI',
      'S.GIRBOVA',
      'S.GRINAUTI-MOLDOVA',
      'S.HADARAUTI',
      'S.LENCAUTI',
      'S.LIPNIC',
      'S.MERESEUCA',
      'S.MIHALASENI',
      'S.NASLAVCEA',
      'S.OCNITA',
      'S.SAUCA',
      'S.UNGURI',
      'S.VALCINET',
      'S.PALADEA',
      'S.RUJNITA',
      'S.BEREZOVCA',
      'S.STALINESTI',
      'S.GRINAUTI',
      'S.GRINAUTI-RAIA',
      'S.REDIUL MARE',
      'S.VEREJENI',
      'S.PAUSTOVA',
      'S.GRINAUTI',
      'S.MAIOVCA',
      'S.CODRENI',
    ],
  },
  {
    region: 'R-UL ORHEI',
    options: [
      'MUN.ORHEI',
      'S.BEREZLOGI',
      'S.BIESTI',
      'S.BOLOHAN',
      'S.BRAVICENI',
      'S.BULAIESTI',
      'S.MIRZESTI',
      'S.CHIPERCENI',
      'S.CIOCILTENI',
      'S.CLISOVA',
      'S.CRIHANA',
      'S.CUCURUZENI',
      'S.DONICI',
      'S.GHETLOVA',
      'S.ISACOVA',
      'S.NECULAIEUCA',
      'S.IVANCEA',
      'S.JORA DE MIJLOC',
      'S.MALAIESTI',
      'S.MITOC',
      'S.MOROZENI',
      'S.PELIVAN',
      'S.PERESECINA',
      'S.PIATRA',
      'S.PODGORENI',
      'S.POHORNICENI',
      'S.POHREBENI',
      'S.PUTINTEI',
      'S.SELISTE',
      'S.STEP-SOCI',
      'S.SUSLENI',
      'S.TELESEU',
      'S.SAMANANCA',
      'S.TREBUJENI',
      'S.VATICI',
      'S.VISCAUTI',
      'S.ZORILE',
      'S.ZAHORENI',
      'S.HIJDIENI',
      'S.CIHORENI',
      'S.SLOBOZIA-HODOROGEA',
      'S.MIRZACI',
      'S.ANDREEVCA',
      'S.VOROTET',
      'S.FEDOREUCA',
      'S.CISMEA',
      'S.CLISOVA NOUA',
      'S.CUCURUZENII DE SUS',
      'S.SIROTA',
      'S.CAMENCEA',
      'S.POCSESTI',
      'S.HULBOACA',
      'S.NOROCENI',
      'S.BRANESTI',
      'S.FURCENI',
      'S.JORA DE JOS',
      'S.JORA DE SUS',
      'S.LOPATNA',
      'S.TIRZIENI',
      'S.BREANOVA',
      'S.JELOBOC',
      'S.IZVOARE',
      'S.SERCANI',
      'S.DISCOVA',
      'S.VIPROVA',
      'S.LUCASEUCA',
      'S.MANA',
      'S.BUDAI',
      'S.BUTUCENI',
      'S.MOROVAIA',
      'S.CURCHI',
      'S.TABARA',
      'S.INCULET',
      'S.OCNITA-RAZESI',
      'S.OCNITA-TARANI',
    ],
  },
  {
    region: 'R-UL REZINA',
    options: [
      'OR.REZINA',
      'S.BUSAUCA',
      'S.CINISEUTI',
      'S.COGILNICENI',
      'S.CUIZAUCA',
      'S.ECHIMAUTI',
      'S.GHIDULENI',
      'S.GORDINESTI',
      'S.HORODISTE',
      'S.IGNATEI',
      'S.LALOVA',
      'S.MATEUTI',
      'S.MESENI',
      'S.MINCENII DE JOS',
      'S.OTAC',
      'S.PAPAUTI',
      'S.LIPCENI',
      'S.PECISTE',
      'S.PERENI',
      'S.PRIPICENI-RAZESI',
      'S.SAHARNA NOUA',
      'S.SIRCOVA',
      'S.SOLONCENI',
      'S.TRIFESTI',
      'S.TAREUCA',
      'S.BOSERNITA',
      'S.CIORNA',
      'S.ROSCANII DE JOS',
      'S.ROSCANII DE SUS',
      'S.SLOBOZIA-HORODISTE',
      'S.NISTRENI',
      'S.TIPOVA',
      'S.MINCENII DE SUS',
      'S.ROSCANI',
      'S.PISCARESTI',
      'S.PRIPICENI-CURCHI',
      'S.BUCIUSCA',
      'S.SAHARNA',
      'S.TARASOVA',
      'S.TAHNAUTI',
      'S.STOHNAIA',
    ],
  },
  {
    region: 'R-UL RISCANI',
    options: [
      'OR.RISCANI',
      'S.ALEXANDRESTI',
      'S.ALUNIS',
      'S.BOROSENII NOI',
      'S.BRANISTE',
      'S.CORLATENI',
      'OR.COSTESTI',
      'S.GALASENI',
      'S.GRINAUTI',
      'S.HILIUTI',
      'S.HORODISTE',
      'S.MALINOVSCOE',
      'S.MIHAILENI',
      'S.PETRUSENI',
      'S.PIRJOTA',
      'S.POCUIMBENI',
      'S.POCIUMBAUTI',
      'S.RACARIA',
      'S.RECEA',
      'S.SINGURENI',
      'S.STURZENI',
      'S.SAPTEBANI',
      'S.SUMNA',
      'S.VASILEUTI',
      'S.VARATIC',
      'S.DURUITOAREA NOUA',
      'S.ZAICANI',
      'S.NIHORENI',
      'S.BALANUL NOU',
      'S.CUCUIETII NOI',
      'S.CUCUIETII VECHI',
      'S.IVANESTI',
      'S.AVRAMENI',
      'S.RETENI',
      'S.RETENI-VASILEUTI',
      'S.DURUITOAREA',
      'S.DAMASCANI',
      'S.PROSCURENI',
      'S.MALAIESTI',
      'S.CIOBANOVCA',
      'S.LUPARIA',
      'S.PASCAUTI',
      'S.DRUTA',
      'S.USUREI',
      'S.RAMAZAN',
      'S.SLOBOZIA-RECEA',
      'S.SVERDIAC',
      'S.BULHAC',
      'S.CEPARIA',
      'S.ARMANCA',
      'S.CIUBARA',
      'S.MIHAILENII NOI',
      'S.MOSENI',
      'S.STIUBEIENI',
      'S.DUMENI',
    ],
  },
  {
    region: 'R-UL SINGEREI',
    options: [
      'OR.SINGEREI',
      'OR.BIRUINTA',
      'S.ALEXANDRENI',
      'S.BALASESTI',
      'S.BILICENII NOI',
      'S.BILICENII VECHI',
      'S.BURSUCENI',
      'S.CHISCARENI',
      'S.CIUCIUIENI',
      'S.COPACENI',
      'S.GRIGORAUCA',
      'S.COSCODENI',
      'S.COTIUJENII MICI',
      'S.CUBOLTA',
      'S.DOBROGEA VECHE',
      'S.DRAGANESTI',
      'S.DUMBRAVITA',
      'S.HECIUL NOU',
      'S.IEZARENII VECHI',
      'S.IZVOARE',
      'S.PEPENI',
      'S.PREPELITA',
      'S.RADOAIA',
      'S.SINGEREII NOI',
      'S.TAURA VECHE',
      'S.MARASESTI',
      'S.VRANESTI',
      'S.GRIGORESTI',
      'S.HECIUL VECHI',
      'S.TIPLESTI',
      'S.TIPLETESTI',
      'S.LIPOVANCA',
      'S.MINDRESTII NOI',
      'S.COADA IAZULUI',
      'S.SLOBOZIA-MAGURA',
      'S.NICOLAEVCA',
      'S.SLOBOZIA-CHISCARENI',
      'S.BREJENI',
      'S.ANTONOVCA',
      'S.EVGHENIEVCA',
      'S.GAVRILOVCA',
      'S.PETROVCA',
      'S.VLADIMIREUCA',
      'S.BOBLETICI',
      'S.FLAMINZENI',
      'S.ALEXEUCA',
      'S.GURA-OITUZ',
      'S.COTOVCA',
      'S.DOBROGEA NOUA',
      'S.CHIRILENI',
      'S.SACAROVCA',
      'S.BOCANCEA-SCHIT',
      'S.VALEA LUI VLAD',
      'S.TRIFANESTI',
      'S.IEZARENII NOI',
      'S.VALEA NOROCULUI',
      'S.MIHAILOVCA',
      'S.PETROPAVLOVCA',
      'S.PEPENII NOI',
      'S.RAZALAI',
      'S.ROMANOVCA',
      'S.SLOVEANCA',
      'S.CLISCAUTI',
      'S.SESTACI',
      'S.MARINESTI',
      'S.TAURA NOUA',
      'S.TAMBULA',
      'S.OCTEABRISCOE',
      'S.PALARIA',
      'S.COZESTI',
    ],
  },
  {
    region: 'R-UL SOROCA',
    options: [
      'S.NIMEREUCA',
      'S.RUDI',
      'S.TATARAUCA VECHE',
      'S.VISOCA',
      'MUN.SOROCA',
      'S.BADICENI',
      'S.BAXANI',
      'S.BULBOCI',
      'S.CAINARII VECHI',
      'S.COSAUTI',
      'S.CREMENCIUG',
      'S.OCLANDA',
      'S.DARCAUTI',
      'S.DUBNA',
      'S.EGORENI',
      'S.HOLOSNITA',
      'S.HRISTICI',
      'S.IAROVA',
      'S.OCOLINA',
      'S.PARCANI',
      'S.PIRLITA',
      'S.RACOVAT',
      'S.REDI-CERESNOVAT',
      'S.REGINA MARIA',
      'S.RUBLENITA',
      'S.SCHINENI',
      'S.VARANCAU',
      'S.STOICANI',
      'S.SEPTELICI',
      'S.SOLCANI',
      'S.VASILCAU',
      'S.TRIFAUTI',
      'S.VADENI',
      'S.VOLOVITA',
      'S.ZASTINCA',
      'S.CERLINA',
      'S.NIORCANI',
      'S.TOLOCANESTI',
      'S.DECEBAL',
      'S.SLOBOZIA NOUA',
      'S.TATARAUCA NOUA',
      'S.GRIGORAUCA',
      'S.BULBOCII NOI',
      'S.FLORICENI',
      'S.IORJNITA',
      'S.LIVEZI',
      'S.SOBARI',
      'S.VALEA',
      'S.DARCAUTII NOI',
      'S.MALCAUTI',
      'S.CURESNITA',
      'S.BALINTI',
      'S.BALINTII NOI',
      'S.TEPILOVA',
      'S.VANTINA',
      'S.VANTINA MICA',
      'S.LUGOVOE',
      'S.RUBLENITA NOUA',
      'S.SCHINENII NOI',
      'S.SLOBOZIA-CREMENE',
      'S.SLOBOZIA-VARANCAU',
      'S.SOLONET',
      'S.CURESNITA NOUA',
      'S.INUNDENI',
      'S.RUSLANOVCA',
      'S.DUMBRAVENI',
      'S.VOLOAVE',
      'S.ALEXANDRU CEL BUN',
    ],
  },
  {
    region: 'R-UL STRASENI',
    options: [
      'S.DOLNA',
      'S.MICLEUSENI',
      'MUN.STRASENI',
      'OR.BUCOVATI',
      'S.CAPRIANA',
      'S.CHIRIANCA',
      'S.CODREANCA',
      'S.COJUSNA',
      'S.GALESTI',
      'S.GHELAUZA',
      'S.GREBLESTI',
      'S.LOZOVA',
      'S.MICAUTI',
      'S.NEGRESTI',
      'S.ONESTI',
      'S.PANASESTI',
      'S.RADENI',
      'S.ROMANESTI',
      'S.RECEA',
      'S.ROSCANI',
      'S.SCORENI',
      'S.SIRETI',
      'S.TATARESTI',
      'S.TIGANESTI',
      'S.VOINOVA',
      'S.VORNICENI',
      'S.ZUBRESTI',
      'S.RASSVET',
      'S.HUZUN',
      'S.FAGURENI',
      'S.LUPA-RECEA',
      'S.GALESTII NOI',
      'S.SACA',
      'S.MARTINESTI',
      'S.STEJARENI',
      'S.GORNOE',
      'S.CIOBANCA',
      'S.DRAGUSENI',
      'S.ZAMCIOGI',
    ],
  },
  {
    region: 'R-UL SOLDANESTI',
    options: [
      'OR.SOLDANESTI',
      'S.ALCEDAR',
      'S.CHIPESCA',
      'S.CLIMAUTII DE JOS',
      'S.COBILEA',
      'S.COTIUJENII MARI',
      'S.CUSMIRCA',
      'S.FUZAUCA',
      'S.GAUZENI',
      'S.GLINJENI',
      'S.MIHULENI',
      'S.OLISCANI',
      'S.PARCANI',
      'S.POHOARNA',
      'S.POIANA',
      'S.RASPOPENI',
      'S.DOBRUSA',
      'S.ROGOJENI',
      'S.SALCIA',
      'S.SAMASCANI',
      'S.SESTACI',
      'S.SIPCA',
      'S.VADUL-RASCOV',
      'S.CURATURA',
      'S.ODAIA',
      'S.COT',
      'S.CUSELAUCA',
      'S.RECESTI',
      'S.ZAHORNA',
      'S.LELINA',
      'S.SOCOLA',
      'S.COBILEA LOC.ST.C.F.',
      'ROGOJENI LOC.ST.C.F.',
    ],
  },
  {
    region: 'R-UL STEFAN VODA',
    options: [
      'OR.STEFAN VODA',
      'S.ALAVA',
      'S.ANTONESTI',
      'S.BREZOAIA',
      'S.CARAHASANI',
      'S.CAPLANI',
      'S.CIOBURCIU',
      'S.COPCEAC',
      'S.CROCMAZ',
      'S.ERMOCLIA',
      'S.FESTELITA',
      'S.MARIANCA DE JOS',
      'S.OLANESTI',
      'S.PALANCA',
      'S.POPEASCA',
      'S.PURCARI',
      'S.RASCAIETI',
      'S.SEMIONOVCA',
      'S.SLOBOZIA',
      'S.STEFANESTI',
      'S.TALMAZA',
      'S.TUDORA',
      'S.VOLINTIRI',
      'S.LAZO',
      'S.VIISOARA',
      'S.RASCAIETII NOI',
    ],
  },
  {
    region: 'R-UL TARACLIA',
    options: [
      'OR.TARACLIA',
      'S.ALBOTA DE JOS',
      'S.ALBOTA DE SUS',
      'S.ALUATU',
      'S.BALABANU',
      'S.BUDAI',
      'S.CAIRACLIA',
      'S.CEALIC',
      'S.CORTEN',
      'S.MUSAITU',
      'S.NOVOSIOLOVCA',
      'S.SALCIA',
      'OR. TVARDITA',
      'S.VALEA PERJEI',
      'S.VINOGRADOVCA',
      'S.HAGICHIOI',
      'S.HIRTOP',
      'S.ROSITA',
      'S.SOFIEVCA',
      'S.SAMURZA',
      'S.OREHOVCA',
      'S.CHIRILOVCA',
      'S.CIUMAI',
      'S.MIRNOE',
      'S.CORTENUL NOU',
      'S.DERMENGI',
    ],
  },
  {
    region: 'R-UL TELENESTI',
    options: [
      'OR.TELENESTI',
      'S.BANESTI',
      'S.BOGZESTI',
      'S.BRINZENII NOI',
      'S.BUDAI',
      'S.CAZANESTI',
      'S.CHISTELNITA',
      'S.CHITCANII VECHI',
      'S.CIULUCANI',
      'S.CISLA',
      'S.CODRUL NOU',
      'S.COROPCENI',
      'S.CRASNASENI',
      'S.GHILICENI',
      'S.HIRISENI',
      'S.INESTI',
      'S.LEUSENI',
      'S.MINDRESTI',
      'S.NEGURENI',
      'S.NUCARENI',
      'S.ORDASEI',
      'S.PISTRUIENI',
      'S.RATUS',
      'S.SARATENII VECHI',
      'S.SCORTENI',
      'S.SUHULUCENI',
      'S.TIRSITEI',
      'S.TINTARENI',
      'S.VASIENI',
      'S.VEREJENI',
      'S.ZGARDESTI',
      'S.MIHALASA',
      'S.MIHALASA NOUA',
      'S.BANESTII NOI',
      'S.BRINZENII VECHI',
      'S.VADUL-LECA',
      'S.VADUL-LECA NOU',
      'S.CHITCANII NOI',
      'S.CUCIOAIA',
      'S.CUCIOAIA NOUA',
      'S.CODRU',
      'S.CHERSAC',
      'S.DOBRUSA',
      'S.HIRTOP',
      'S.PISTRUIENII NOI',
      'S.MINDRA',
      'S.SARATENII NOI',
      'S.ZAICANI',
      'S.ZAICANII NOI',
      'S.ZAHAREUCA',
      'S.GHERMANESTI',
      'S.FLUTURA',
      'S.BONDAREUCA',
      'S.CIOFU',
    ],
  },
  {
    region: 'R-UL UNGHENI',
    options: [
      'MUN.UNGHENI',
      'OR.CORNESTI',
      'S.AGRONOMOVCA',
      'S.ALEXEEVCA',
      'S.BOGHENII NOI',
      'S.BUCIUMENI',
      'S.BUMBATA',
      'S.BUSILA',
      'S.CETIRENI',
      'S.CHIRILENI',
      'S.CIOROPCANI',
      'S.CONDRATESTI',
      'S.CORNESTI',
      'S.CORNOVA',
      'S.COSTULENI',
      'S.FLORITOAIA VECHE',
      'S.HIRCESTI',
      'S.LIDOVCA',
      'S.ROMANOVCA',
      'S.SAGHIENI',
      'S.AZULENII VECHI',
      'S.BOGHENII VECHI',
      'S.BLINDESTI',
      'S.BUCIUMENI',
      'S.BULHAC',
      'S.BUZDUGANII DE JOS',
      'S.BUZDUGANII DE SUS',
      'S.COASENI',
      'S.CONDRATESTI',
      'S.COSENI',
      'S.COSTULENI',
      'S.CURTOAIA',
      'S.DRUJBA',
      'S.ELIZAVETOVCA',
      'S.FLORENI',
      'S.FRASINESTI',
      'S.GHERMAN',
      'S.GROZASCA',
      'S.GRASENI',
      'S.HIRCESTI',
      'S.HRISTOFOROVCA',
      'S.IZVORENI',
      'S.LEORDOAIA',
      'S.LIDOVCA',
      'S.MACARESTI',
      'S.MANOILESTI',
      'S.MEDELENI',
      'S.MIRCESTI',
      'S.MORENII NOI',
      'S.MORENII VECHI',
      'S.NAPADENI',
      'S.NEGURENII NOI',
      'S.NEGURENII VECHI',
      'S.NOVAIA NICOLAEVCA',
      'S.PETRESTI',
      'S.PIRLITA',
      'S.PLANCANI',
      'S.POIANA',
      'S.POJARNA',
      'S.REZINA',
      'S.SAGHIENI',
      'S.SCULENI',
      'S.SEMENI',
      'S.SICOVAT',
      'S.SINESTI',
      'S.STOLNICENI',
      'S.TESCURENI',
      'S.TIGHIRA',
      'S.TODIRESTI',
      'S.UNTESTI',
      'S.VALEA MARE',
      'S.VEVERITA',
      'S.VULPESTI',
      'S.ZAGARANCEA',
      'S.ZAZULENII VECHI',
      'S.ZAZULENII NOI',
      'BUCIUMENI LOC.ST.C.F.',
      'PETRESTI LOC.ST.C.F.',
    ],
  },
  {
    region: 'GAGAUZIA',
    options: [
      'MUN.COMRAT',
      'MUN.CEADIR-LUNGA',
      'OR.VULCANESTI',
      'S.AVDARMA',
      'S.BAURCI',
      'S.BESALMA',
      'S.BESGHIOZ',
      'S.BUGEAC',
      'S.CARBALIA',
      'S.CAZACLIA',
      'S.CHIOSELIA RUSA',
      'S.CHIRIET-LUNGA',
      'S.CHIRSOVA',
      'S.CIOC-MAIDAN',
      'S.CISMICHIOI',
      'S.CONGAZ',
      'S.CONGAZCICUL DE SUS',
      'S.COPCEAC',
      'S.COTOVSCOE',
      'S.DEZGHINGEA',
      'S.ETULIA',
      'S.FERAPONTIEVCA',
      'S.GAIDAR',
      'S.JOLTAI',
      'S.SVETLII',
      'S.TOMAI',
      'S.CONGAZCICUL DE JOS',
      'S.DUDULESTI',
      'S.ETULIA NOUA',
      'S.ALEXEEVCA',
      'VULCANESTI LOC.ST.C.F.',
      'ETULIA LOC.ST.C.F.',
    ],
  },
  {
    region: 'TDS NISTRULUI',
    options: [
      'MUN.TIRASPOL',
      'OR.DNESTROVSC',
      'OR.TIRASPOLUL NOU',
      'OR.CAMENCA',
      'S.CATERINOVCA',
      'S.CRASNII OCTEABRI',
      'S.CUZMIN',
      'S.HRISTOVAIA',
      'S.HRUSCA',
      'S.OCNITA',
      'S.PODOIMA',
      'S.RASCOV',
      'S.ROTARI',
      'S.SEVERINOVCA',
      'S.SLOBOZIA-RASCOV',
      'S.VALEA ADINCA',
      'OR.DUBASARI',
      'S.COMISAROVCA NOUA',
      'S.CRASNII VINOGRADARI',
      'S.DOIBANI I',
      'S.DUBAU',
      'S.DZERJINSCOE',
      'S.GOIAN',
      'S.HARMATCA',
      'S.LUNGA',
      'S.TIBULEUCA',
      'OR.GRIGORIOPOL',
      'OR.MAIAC',
      'S.BICIOC',
      'S.BUTOR',
      'S.CARMANOVA',
      'S.COLOSOVA',
      'S.CRASNOGORCA',
      'S.DELACAU',
      'S.HIRTOP',
      'S.HLINAIA',
      'S.MALAIESTI',
      'S.SPEIA',
      'S.SIPCA',
      'S.TASLIC',
      'S.TEIU',
      'S.VINOGRADNOE',
      'OR.RIBNITA',
      'S.ANDREEVCA',
      'S.BELOCI',
      'S.BROSTENI',
      'S.BUTUCENI',
      'S.COBASNA',
      'S.CRASNENCOE',
      'S.GHIDIRIM',
      'S.HARABA',
      'S.HIRJAU',
      'S.JURA',
      'S.LENIN',
      'S.MIHAILOVCA',
      'S.MOCRA',
      'S.MOLOCHISUL MARE',
      'S.OFATINTI',
      'S.PLOPI',
      'S.POPENCU',
      'S.SOVIETSCOE',
      'S.STROIESTI',
      'S.ULMU',
      'S.VADUL TURCULUI',
      'S.VARANCAU',
      'OR.SLOBOZIA',
      'OR.CRASNOE',
      'S.BLIJNII HUTOR',
      'S.CARAGAS',
      'S.CIOBURCIU',
      'S.COROTNA',
      'S.FRUNZA',
      'S.HLINAIA',
      'S.NEZAVERTAILOVCA',
      'S.PARCANI',
      'S.PERVOMAISC',
      'S.SUCLEIA',
      'S.TIRNAUCA',
      'S.VLADIMIROVCA',
      'S.SOLNECINOE',
      'S.SADCHI',
      'S.ALEXANDROVCA',
      'S.VOITOVCA',
      'S.FRUNZAUCA',
      'S.PODOIMITA',
      'S.IANTARNOE',
      'S.BODENI',
      'S.SOCOLOVCA',
      'S.CONSTANTINOVCA',
      'S.BOSCA',
      'S.COSNITA NOUA',
      'S.POHREBEA NOUA',
      'S.AFANASIEVCA',
      'S.ALEXANDROVCA NOUA',
      'S.CALINOVCA',
      'S.LUNGA NOUA',
      'S.COICOVA',
      'S.DOIBANI II',
      'S.GOIANUL NOU',
      'S.IAGORLIC',
      'S.CRASNOE',
      'S.NOVOVLADIMIROVCA',
      'S.INDIA',
      'S.COTOVCA',
      'S.FEDOSEEVCA',
      'S.MOCEAROVCA',
      'S.CRASNAIA BESARABIA',
      'S.POBEDA',
      'S.CRASNAIA GORCA',
      'S.BRUSLACHI',
      'S.MARIAN',
      'S.MOCREACHI',
      'S.CERNITA',
      'S.VESIOLOE',
      'S.TOCMAGIU',
      'S.PICALOVA',
      'S.SMALENA',
      'S.SUHAIA RIBNITA',
      'S.DIMITROVA',
      'S.IVANOVCA',
      'S.MIHAILOVCA NOUA',
      'S.SARATEI',
      'S.PERVOMAISC',
      'S.POBEDA',
      'S.STANISLAVCA',
      'S.BASARABCA',
      'S.SEVCENCO',
      'S.ZAPOROJET',
      'S.NOVAIA JIZNI',
      'S.CHIROV',
      'S.VLADIMIROVCA',
      'S.ZAZULENI',
      'S.VASILIEVCA',
      'S.LISAIA GORA',
      'S.ULMUL MIC',
      'S.MOLOCHISUL MIC',
      'S.BUSCHI',
      'S.GHERSUNOVCA',
      'COBASNA LOC.ST.C.F.',
      'S.ANDRIASEVCA NOUA',
      'S.ANDRIASEVCA VECHE',
      'S.NOVOCOTOVSC',
      'S.NOVOSAVITCAIA LOC.ST.C.F.',
      'S.PRIOZIORNOE',
      'S.UIUTNOE',
      'S.CONSTANTINOVCA',
      'S.NICOLSCOE',
    ],
  },
]
