export const TRIP_PURPOSE = [
  'TRVL', // 'Turism (călătorie)',
  'ADV', // Sport Agrement
  'SKI', // 'Odihnă activă (ski)',
  'BIZZ', // 'Afaceri',
  'STUDY', // 'Studii',
  'WORK', // 'Muncă (servicii, risc redus de accident)',
  // 'GSTRB', // 'Muncă (fizic, risc sporit de accident)',
]
export const SPORT_TYPES = [
  'acrobatics',
  'climbing',
  'easy-athletics',
  'auto-moto-sport',
  'badminton',
  'basket-ball',
  'biathlon',
  'boxing',
  'cycling',
  'dance',
  'diving',
  'football',
  'freestyle',
  'artistic-gymnastics',
  'golf',
  'dumb-bell',
  'handball',
  'horse-racing',
  'hockey',
  'swimming',
  'battles',
  'motobol',
  'sky-diving',
  'ice-diving',
  'polo',
  'rugby',
  'ski-jumping',
  'water-jumping',
  'ski',
  'water-ski',
  'snowboard',
  'aviation-sports',
  'equestrian-sports',
  'team-sports',
  'tennis',
  'mountain-tourism',
  'rowing',
  'volley-ball',
  'windsurfing',
  'wrestling',
  'yachting',
]
